// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sensor/basic.proto

/*
Package choreo is a generated protocol buffer package.

It is generated from these files:
	sensor/basic.proto

It has these top-level messages:
	FluidPressure
	Illuminance
	Humidity
	Temperature
	TimeReference
*/
package choreo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import choreo1 "primitive"
import choreo2 "primitive"
import choreo3 "primitive"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FluidPressure struct {
	Header        *choreo2.Header  `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	FluidPressure *choreo1.Float64 `protobuf:"bytes,2,opt,name=fluid_pressure,json=fluidPressure" json:"fluid_pressure,omitempty"`
	Variance      *choreo1.Float64 `protobuf:"bytes,3,opt,name=variance" json:"variance,omitempty"`
}

func (m *FluidPressure) Reset()                    { *m = FluidPressure{} }
func (m *FluidPressure) String() string            { return proto.CompactTextString(m) }
func (*FluidPressure) ProtoMessage()               {}
func (*FluidPressure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FluidPressure) GetHeader() *choreo2.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FluidPressure) GetFluidPressure() *choreo1.Float64 {
	if m != nil {
		return m.FluidPressure
	}
	return nil
}

func (m *FluidPressure) GetVariance() *choreo1.Float64 {
	if m != nil {
		return m.Variance
	}
	return nil
}

type Illuminance struct {
	Header      *choreo2.Header  `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Illuminance *choreo1.Float64 `protobuf:"bytes,2,opt,name=illuminance" json:"illuminance,omitempty"`
	Variance    *choreo1.Float64 `protobuf:"bytes,3,opt,name=variance" json:"variance,omitempty"`
}

func (m *Illuminance) Reset()                    { *m = Illuminance{} }
func (m *Illuminance) String() string            { return proto.CompactTextString(m) }
func (*Illuminance) ProtoMessage()               {}
func (*Illuminance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Illuminance) GetHeader() *choreo2.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Illuminance) GetIlluminance() *choreo1.Float64 {
	if m != nil {
		return m.Illuminance
	}
	return nil
}

func (m *Illuminance) GetVariance() *choreo1.Float64 {
	if m != nil {
		return m.Variance
	}
	return nil
}

type Humidity struct {
	Header           *choreo2.Header  `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	RelativeHumidity *choreo1.Float64 `protobuf:"bytes,2,opt,name=relative_humidity,json=relativeHumidity" json:"relative_humidity,omitempty"`
	Variance         *choreo1.Float64 `protobuf:"bytes,3,opt,name=variance" json:"variance,omitempty"`
}

func (m *Humidity) Reset()                    { *m = Humidity{} }
func (m *Humidity) String() string            { return proto.CompactTextString(m) }
func (*Humidity) ProtoMessage()               {}
func (*Humidity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Humidity) GetHeader() *choreo2.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Humidity) GetRelativeHumidity() *choreo1.Float64 {
	if m != nil {
		return m.RelativeHumidity
	}
	return nil
}

func (m *Humidity) GetVariance() *choreo1.Float64 {
	if m != nil {
		return m.Variance
	}
	return nil
}

type Temperature struct {
	Header      *choreo2.Header  `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Temperature *choreo1.Float64 `protobuf:"bytes,2,opt,name=temperature" json:"temperature,omitempty"`
	Variance    *choreo1.Float64 `protobuf:"bytes,3,opt,name=variance" json:"variance,omitempty"`
}

func (m *Temperature) Reset()                    { *m = Temperature{} }
func (m *Temperature) String() string            { return proto.CompactTextString(m) }
func (*Temperature) ProtoMessage()               {}
func (*Temperature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Temperature) GetHeader() *choreo2.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Temperature) GetTemperature() *choreo1.Float64 {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Temperature) GetVariance() *choreo1.Float64 {
	if m != nil {
		return m.Variance
	}
	return nil
}

type TimeReference struct {
	Header  *choreo2.Header            `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	TimeRef *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=time_ref,json=timeRef" json:"time_ref,omitempty"`
	Source  *choreo3.String            `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
}

func (m *TimeReference) Reset()                    { *m = TimeReference{} }
func (m *TimeReference) String() string            { return proto.CompactTextString(m) }
func (*TimeReference) ProtoMessage()               {}
func (*TimeReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TimeReference) GetHeader() *choreo2.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TimeReference) GetTimeRef() *google_protobuf.Timestamp {
	if m != nil {
		return m.TimeRef
	}
	return nil
}

func (m *TimeReference) GetSource() *choreo3.String {
	if m != nil {
		return m.Source
	}
	return nil
}

func init() {
	proto.RegisterType((*FluidPressure)(nil), "choreo.FluidPressure")
	proto.RegisterType((*Illuminance)(nil), "choreo.Illuminance")
	proto.RegisterType((*Humidity)(nil), "choreo.Humidity")
	proto.RegisterType((*Temperature)(nil), "choreo.Temperature")
	proto.RegisterType((*TimeReference)(nil), "choreo.TimeReference")
}

func init() { proto.RegisterFile("sensor/basic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x42, 0x2d, 0x13, 0x5a, 0x35, 0xa0, 0x94, 0x5e, 0x94, 0x1e, 0x44, 0x10, 0x12,
	0xea, 0x9f, 0x9e, 0x3c, 0x97, 0x7a, 0x93, 0xd8, 0x7b, 0xd9, 0xb6, 0x93, 0x76, 0x20, 0x9b, 0x0d,
	0xb3, 0x9b, 0x82, 0x1f, 0x44, 0x4f, 0xfa, 0x5d, 0x25, 0xc9, 0x26, 0xad, 0x68, 0xa1, 0x39, 0xee,
	0xdb, 0xf7, 0x66, 0x7f, 0xec, 0xf0, 0xc0, 0xd3, 0x98, 0x68, 0xc5, 0xc1, 0x5c, 0x68, 0x5a, 0xf8,
	0x29, 0x2b, 0xa3, 0xbc, 0xd6, 0x62, 0xad, 0x18, 0x55, 0xff, 0x6a, 0xa5, 0xd4, 0x2a, 0xc6, 0xa0,
	0x50, 0xe7, 0x59, 0x14, 0x18, 0x92, 0xa8, 0x8d, 0x90, 0x69, 0x69, 0xec, 0x5f, 0xa4, 0x4c, 0x92,
	0x0c, 0x6d, 0x30, 0x88, 0x62, 0x25, 0x8c, 0x95, 0x2f, 0xb7, 0xf2, 0x1a, 0xc5, 0x12, 0xf9, 0xaf,
	0xae, 0x0d, 0x53, 0xb2, 0x2a, 0xf5, 0xc1, 0x97, 0x03, 0x9d, 0x71, 0x9c, 0xd1, 0xf2, 0x95, 0x51,
	0xeb, 0x8c, 0xd1, 0xbb, 0x81, 0x56, 0x99, 0xec, 0x39, 0xd7, 0xce, 0xad, 0x7b, 0xdf, 0xf5, 0x4b,
	0x24, 0x7f, 0x52, 0xa8, 0xa1, 0xbd, 0xf5, 0x46, 0xd0, 0x8d, 0xf2, 0xe0, 0x2c, 0xb5, 0xc9, 0xde,
	0x51, 0xe1, 0x3f, 0xad, 0xfc, 0xe3, 0x1c, 0x6b, 0xf4, 0x18, 0x76, 0xa2, 0x5f, 0xf3, 0xef, 0xa0,
	0xbd, 0x11, 0x4c, 0x22, 0x59, 0x60, 0xef, 0xf8, 0xff, 0x44, 0x6d, 0x18, 0x7c, 0x38, 0xe0, 0xbe,
	0xc4, 0x71, 0x26, 0x29, 0xc9, 0xcf, 0x07, 0xc3, 0x0d, 0xc1, 0xa5, 0x6d, 0x6c, 0x1f, 0xd9, 0xae,
	0xa7, 0x19, 0xd7, 0xb7, 0x03, 0xed, 0x49, 0x26, 0x69, 0x49, 0xe6, 0xfd, 0x60, 0xa8, 0x67, 0x38,
	0x67, 0x8c, 0x45, 0xbe, 0x84, 0xd9, 0xda, 0x86, 0xf7, 0xa1, 0x9d, 0x55, 0xce, 0xfa, 0x95, 0xc6,
	0xff, 0x36, 0x45, 0x99, 0x22, 0x0b, 0xd3, 0x64, 0xa9, 0x43, 0x70, 0xcd, 0x36, 0xb6, 0xf7, 0xdf,
	0x76, 0x3c, 0xcd, 0xb8, 0x3e, 0x1d, 0xe8, 0x4c, 0x49, 0x62, 0x88, 0x11, 0x32, 0x36, 0xd9, 0xe8,
	0x13, 0xb4, 0xf3, 0x0a, 0xcc, 0x18, 0x23, 0x8b, 0xd5, 0xf7, 0xcb, 0x8e, 0xf8, 0x55, 0x47, 0xfc,
	0x69, 0xd5, 0x91, 0xf0, 0xc4, 0x94, 0x8f, 0xe4, 0xe3, 0xb5, 0xca, 0xb8, 0x66, 0xab, 0xc7, 0xbf,
	0x15, 0x2d, 0x08, 0xed, 0xed, 0xbc, 0x55, 0x0c, 0x79, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x93,
	0x28, 0xde, 0x11, 0x94, 0x03, 0x00, 0x00,
}
