// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geometric/vector.proto

/*
Package choreo is a generated protocol buffer package.

It is generated from these files:
	geometric/vector.proto

It has these top-level messages:
	Vector3Stamped
	Vector3
*/
package choreo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import choreo1 "primitive"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector3Stamped struct {
	Header *choreo1.Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Vector *Vector3        `protobuf:"bytes,2,opt,name=vector" json:"vector,omitempty"`
}

func (m *Vector3Stamped) Reset()                    { *m = Vector3Stamped{} }
func (m *Vector3Stamped) String() string            { return proto.CompactTextString(m) }
func (*Vector3Stamped) ProtoMessage()               {}
func (*Vector3Stamped) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vector3Stamped) GetHeader() *choreo1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Vector3Stamped) GetVector() *Vector3 {
	if m != nil {
		return m.Vector
	}
	return nil
}

type Vector3 struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z" json:"z,omitempty"`
}

func (m *Vector3) Reset()                    { *m = Vector3{} }
func (m *Vector3) String() string            { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()               {}
func (*Vector3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Vector3) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector3) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector3) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*Vector3Stamped)(nil), "choreo.Vector3Stamped")
	proto.RegisterType((*Vector3)(nil), "choreo.Vector3")
}

func init() { proto.RegisterFile("geometric/vector.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4f, 0xcd, 0xcf,
	0x4d, 0x2d, 0x29, 0xca, 0x4c, 0xd6, 0x2f, 0x4b, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xc8, 0x2f, 0x4a, 0xcd, 0x97, 0x12, 0x2b, 0x28, 0xca, 0xcc,
	0xcd, 0x2c, 0xc9, 0x2c, 0x4b, 0xd5, 0xcf, 0x48, 0x4d, 0x4c, 0x49, 0x85, 0xca, 0x2b, 0x25, 0x72,
	0xf1, 0x85, 0x81, 0xd5, 0x1b, 0x07, 0x97, 0x24, 0xe6, 0x16, 0xa4, 0xa6, 0x08, 0xa9, 0x71, 0xb1,
	0x41, 0x54, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe9, 0x41, 0x8c, 0xd0, 0xf3, 0x00,
	0x8b, 0x06, 0x41, 0x65, 0x85, 0xd4, 0xb9, 0xd8, 0x20, 0x36, 0x49, 0x30, 0x81, 0xd5, 0xf1, 0xc3,
	0xd4, 0x41, 0xcd, 0x0b, 0x82, 0x4a, 0x2b, 0x19, 0x73, 0xb1, 0x43, 0x85, 0x84, 0x78, 0xb8, 0x18,
	0x2b, 0xc0, 0xc6, 0x32, 0x06, 0x31, 0x56, 0x80, 0x78, 0x95, 0x60, 0xcd, 0x8c, 0x41, 0x8c, 0x95,
	0x20, 0x5e, 0x95, 0x04, 0x33, 0x84, 0x57, 0x95, 0xc4, 0x06, 0x76, 0x9e, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x45, 0xd0, 0x11, 0xf6, 0xd8, 0x00, 0x00, 0x00,
}
