// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action/action.proto

package choreo;

public final class Action {
  private Action() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GoalIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:choreo.GoalID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp stamp = 1;</code>
     */
    boolean hasStamp();
    /**
     * <code>.google.protobuf.Timestamp stamp = 1;</code>
     */
    com.google.protobuf.Timestamp getStamp();
    /**
     * <code>.google.protobuf.Timestamp stamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStampOrBuilder();

    /**
     * <code>.choreo.String id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>.choreo.String id = 2;</code>
     */
    choreo.StringOuterClass.String getId();
    /**
     * <code>.choreo.String id = 2;</code>
     */
    choreo.StringOuterClass.StringOrBuilder getIdOrBuilder();
  }
  /**
   * Protobuf type {@code choreo.GoalID}
   */
  public  static final class GoalID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:choreo.GoalID)
      GoalIDOrBuilder {
    // Use GoalID.newBuilder() to construct.
    private GoalID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoalID() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GoalID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (stamp_ != null) {
                subBuilder = stamp_.toBuilder();
              }
              stamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stamp_);
                stamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              choreo.StringOuterClass.String.Builder subBuilder = null;
              if (id_ != null) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(choreo.StringOuterClass.String.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return choreo.Action.internal_static_choreo_GoalID_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return choreo.Action.internal_static_choreo_GoalID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              choreo.Action.GoalID.class, choreo.Action.GoalID.Builder.class);
    }

    public static final int STAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp stamp_;
    /**
     * <code>.google.protobuf.Timestamp stamp = 1;</code>
     */
    public boolean hasStamp() {
      return stamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp stamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getStamp() {
      return stamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : stamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp stamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStampOrBuilder() {
      return getStamp();
    }

    public static final int ID_FIELD_NUMBER = 2;
    private choreo.StringOuterClass.String id_;
    /**
     * <code>.choreo.String id = 2;</code>
     */
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.choreo.String id = 2;</code>
     */
    public choreo.StringOuterClass.String getId() {
      return id_ == null ? choreo.StringOuterClass.String.getDefaultInstance() : id_;
    }
    /**
     * <code>.choreo.String id = 2;</code>
     */
    public choreo.StringOuterClass.StringOrBuilder getIdOrBuilder() {
      return getId();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stamp_ != null) {
        output.writeMessage(1, getStamp());
      }
      if (id_ != null) {
        output.writeMessage(2, getId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStamp());
      }
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getId());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof choreo.Action.GoalID)) {
        return super.equals(obj);
      }
      choreo.Action.GoalID other = (choreo.Action.GoalID) obj;

      boolean result = true;
      result = result && (hasStamp() == other.hasStamp());
      if (hasStamp()) {
        result = result && getStamp()
            .equals(other.getStamp());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStamp()) {
        hash = (37 * hash) + STAMP_FIELD_NUMBER;
        hash = (53 * hash) + getStamp().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static choreo.Action.GoalID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.Action.GoalID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.Action.GoalID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(choreo.Action.GoalID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code choreo.GoalID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:choreo.GoalID)
        choreo.Action.GoalIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return choreo.Action.internal_static_choreo_GoalID_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return choreo.Action.internal_static_choreo_GoalID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                choreo.Action.GoalID.class, choreo.Action.GoalID.Builder.class);
      }

      // Construct using choreo.Action.GoalID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (stampBuilder_ == null) {
          stamp_ = null;
        } else {
          stamp_ = null;
          stampBuilder_ = null;
        }
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          id_ = null;
          idBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return choreo.Action.internal_static_choreo_GoalID_descriptor;
      }

      public choreo.Action.GoalID getDefaultInstanceForType() {
        return choreo.Action.GoalID.getDefaultInstance();
      }

      public choreo.Action.GoalID build() {
        choreo.Action.GoalID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public choreo.Action.GoalID buildPartial() {
        choreo.Action.GoalID result = new choreo.Action.GoalID(this);
        if (stampBuilder_ == null) {
          result.stamp_ = stamp_;
        } else {
          result.stamp_ = stampBuilder_.build();
        }
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof choreo.Action.GoalID) {
          return mergeFrom((choreo.Action.GoalID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(choreo.Action.GoalID other) {
        if (other == choreo.Action.GoalID.getDefaultInstance()) return this;
        if (other.hasStamp()) {
          mergeStamp(other.getStamp());
        }
        if (other.hasId()) {
          mergeId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        choreo.Action.GoalID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (choreo.Action.GoalID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Timestamp stamp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> stampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public boolean hasStamp() {
        return stampBuilder_ != null || stamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public com.google.protobuf.Timestamp getStamp() {
        if (stampBuilder_ == null) {
          return stamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : stamp_;
        } else {
          return stampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public Builder setStamp(com.google.protobuf.Timestamp value) {
        if (stampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stamp_ = value;
          onChanged();
        } else {
          stampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public Builder setStamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (stampBuilder_ == null) {
          stamp_ = builderForValue.build();
          onChanged();
        } else {
          stampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public Builder mergeStamp(com.google.protobuf.Timestamp value) {
        if (stampBuilder_ == null) {
          if (stamp_ != null) {
            stamp_ =
              com.google.protobuf.Timestamp.newBuilder(stamp_).mergeFrom(value).buildPartial();
          } else {
            stamp_ = value;
          }
          onChanged();
        } else {
          stampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public Builder clearStamp() {
        if (stampBuilder_ == null) {
          stamp_ = null;
          onChanged();
        } else {
          stamp_ = null;
          stampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStampBuilder() {
        
        onChanged();
        return getStampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStampOrBuilder() {
        if (stampBuilder_ != null) {
          return stampBuilder_.getMessageOrBuilder();
        } else {
          return stamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : stamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp stamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStampFieldBuilder() {
        if (stampBuilder_ == null) {
          stampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStamp(),
                  getParentForChildren(),
                  isClean());
          stamp_ = null;
        }
        return stampBuilder_;
      }

      private choreo.StringOuterClass.String id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.StringOuterClass.String, choreo.StringOuterClass.String.Builder, choreo.StringOuterClass.StringOrBuilder> idBuilder_;
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public boolean hasId() {
        return idBuilder_ != null || id_ != null;
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public choreo.StringOuterClass.String getId() {
        if (idBuilder_ == null) {
          return id_ == null ? choreo.StringOuterClass.String.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public Builder setId(choreo.StringOuterClass.String value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public Builder setId(
          choreo.StringOuterClass.String.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public Builder mergeId(choreo.StringOuterClass.String value) {
        if (idBuilder_ == null) {
          if (id_ != null) {
            id_ =
              choreo.StringOuterClass.String.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          id_ = null;
          idBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public choreo.StringOuterClass.String.Builder getIdBuilder() {
        
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      public choreo.StringOuterClass.StringOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              choreo.StringOuterClass.String.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.choreo.String id = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.StringOuterClass.String, choreo.StringOuterClass.String.Builder, choreo.StringOuterClass.StringOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.StringOuterClass.String, choreo.StringOuterClass.String.Builder, choreo.StringOuterClass.StringOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:choreo.GoalID)
    }

    // @@protoc_insertion_point(class_scope:choreo.GoalID)
    private static final choreo.Action.GoalID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new choreo.Action.GoalID();
    }

    public static choreo.Action.GoalID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoalID>
        PARSER = new com.google.protobuf.AbstractParser<GoalID>() {
      public GoalID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GoalID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoalID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoalID> getParserForType() {
      return PARSER;
    }

    public choreo.Action.GoalID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GoalStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:choreo.GoalStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.choreo.GoalID goal_id = 1;</code>
     */
    boolean hasGoalId();
    /**
     * <code>.choreo.GoalID goal_id = 1;</code>
     */
    choreo.Action.GoalID getGoalId();
    /**
     * <code>.choreo.GoalID goal_id = 1;</code>
     */
    choreo.Action.GoalIDOrBuilder getGoalIdOrBuilder();

    /**
     * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
     */
    int getStatusValue();
    /**
     * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
     */
    choreo.Action.GoalStatus.GoalStatusType getStatus();

    /**
     * <code>.choreo.String text = 3;</code>
     */
    boolean hasText();
    /**
     * <code>.choreo.String text = 3;</code>
     */
    choreo.StringOuterClass.String getText();
    /**
     * <code>.choreo.String text = 3;</code>
     */
    choreo.StringOuterClass.StringOrBuilder getTextOrBuilder();
  }
  /**
   * Protobuf type {@code choreo.GoalStatus}
   */
  public  static final class GoalStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:choreo.GoalStatus)
      GoalStatusOrBuilder {
    // Use GoalStatus.newBuilder() to construct.
    private GoalStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoalStatus() {
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GoalStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              choreo.Action.GoalID.Builder subBuilder = null;
              if (goalId_ != null) {
                subBuilder = goalId_.toBuilder();
              }
              goalId_ = input.readMessage(choreo.Action.GoalID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(goalId_);
                goalId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 26: {
              choreo.StringOuterClass.String.Builder subBuilder = null;
              if (text_ != null) {
                subBuilder = text_.toBuilder();
              }
              text_ = input.readMessage(choreo.StringOuterClass.String.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(text_);
                text_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return choreo.Action.internal_static_choreo_GoalStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return choreo.Action.internal_static_choreo_GoalStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              choreo.Action.GoalStatus.class, choreo.Action.GoalStatus.Builder.class);
    }

    /**
     * Protobuf enum {@code choreo.GoalStatus.GoalStatusType}
     */
    public enum GoalStatusType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PENDING = 0;</code>
       */
      PENDING(0),
      /**
       * <code>ACTIVE = 1;</code>
       */
      ACTIVE(1),
      /**
       * <code>PREEMPTED = 2;</code>
       */
      PREEMPTED(2),
      /**
       * <code>SUCCEEDED = 3;</code>
       */
      SUCCEEDED(3),
      /**
       * <code>ABORTED = 4;</code>
       */
      ABORTED(4),
      /**
       * <code>REJECTED = 5;</code>
       */
      REJECTED(5),
      /**
       * <code>PREEMPTING = 6;</code>
       */
      PREEMPTING(6),
      /**
       * <code>RECALLING = 7;</code>
       */
      RECALLING(7),
      /**
       * <code>RECALLED = 8;</code>
       */
      RECALLED(8),
      /**
       * <code>LOST = 9;</code>
       */
      LOST(9),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PENDING = 0;</code>
       */
      public static final int PENDING_VALUE = 0;
      /**
       * <code>ACTIVE = 1;</code>
       */
      public static final int ACTIVE_VALUE = 1;
      /**
       * <code>PREEMPTED = 2;</code>
       */
      public static final int PREEMPTED_VALUE = 2;
      /**
       * <code>SUCCEEDED = 3;</code>
       */
      public static final int SUCCEEDED_VALUE = 3;
      /**
       * <code>ABORTED = 4;</code>
       */
      public static final int ABORTED_VALUE = 4;
      /**
       * <code>REJECTED = 5;</code>
       */
      public static final int REJECTED_VALUE = 5;
      /**
       * <code>PREEMPTING = 6;</code>
       */
      public static final int PREEMPTING_VALUE = 6;
      /**
       * <code>RECALLING = 7;</code>
       */
      public static final int RECALLING_VALUE = 7;
      /**
       * <code>RECALLED = 8;</code>
       */
      public static final int RECALLED_VALUE = 8;
      /**
       * <code>LOST = 9;</code>
       */
      public static final int LOST_VALUE = 9;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static GoalStatusType valueOf(int value) {
        return forNumber(value);
      }

      public static GoalStatusType forNumber(int value) {
        switch (value) {
          case 0: return PENDING;
          case 1: return ACTIVE;
          case 2: return PREEMPTED;
          case 3: return SUCCEEDED;
          case 4: return ABORTED;
          case 5: return REJECTED;
          case 6: return PREEMPTING;
          case 7: return RECALLING;
          case 8: return RECALLED;
          case 9: return LOST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<GoalStatusType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          GoalStatusType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<GoalStatusType>() {
              public GoalStatusType findValueByNumber(int number) {
                return GoalStatusType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return choreo.Action.GoalStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final GoalStatusType[] VALUES = values();

      public static GoalStatusType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private GoalStatusType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:choreo.GoalStatus.GoalStatusType)
    }

    public static final int GOAL_ID_FIELD_NUMBER = 1;
    private choreo.Action.GoalID goalId_;
    /**
     * <code>.choreo.GoalID goal_id = 1;</code>
     */
    public boolean hasGoalId() {
      return goalId_ != null;
    }
    /**
     * <code>.choreo.GoalID goal_id = 1;</code>
     */
    public choreo.Action.GoalID getGoalId() {
      return goalId_ == null ? choreo.Action.GoalID.getDefaultInstance() : goalId_;
    }
    /**
     * <code>.choreo.GoalID goal_id = 1;</code>
     */
    public choreo.Action.GoalIDOrBuilder getGoalIdOrBuilder() {
      return getGoalId();
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
     */
    public choreo.Action.GoalStatus.GoalStatusType getStatus() {
      choreo.Action.GoalStatus.GoalStatusType result = choreo.Action.GoalStatus.GoalStatusType.valueOf(status_);
      return result == null ? choreo.Action.GoalStatus.GoalStatusType.UNRECOGNIZED : result;
    }

    public static final int TEXT_FIELD_NUMBER = 3;
    private choreo.StringOuterClass.String text_;
    /**
     * <code>.choreo.String text = 3;</code>
     */
    public boolean hasText() {
      return text_ != null;
    }
    /**
     * <code>.choreo.String text = 3;</code>
     */
    public choreo.StringOuterClass.String getText() {
      return text_ == null ? choreo.StringOuterClass.String.getDefaultInstance() : text_;
    }
    /**
     * <code>.choreo.String text = 3;</code>
     */
    public choreo.StringOuterClass.StringOrBuilder getTextOrBuilder() {
      return getText();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (goalId_ != null) {
        output.writeMessage(1, getGoalId());
      }
      if (status_ != choreo.Action.GoalStatus.GoalStatusType.PENDING.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (text_ != null) {
        output.writeMessage(3, getText());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (goalId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGoalId());
      }
      if (status_ != choreo.Action.GoalStatus.GoalStatusType.PENDING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (text_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getText());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof choreo.Action.GoalStatus)) {
        return super.equals(obj);
      }
      choreo.Action.GoalStatus other = (choreo.Action.GoalStatus) obj;

      boolean result = true;
      result = result && (hasGoalId() == other.hasGoalId());
      if (hasGoalId()) {
        result = result && getGoalId()
            .equals(other.getGoalId());
      }
      result = result && status_ == other.status_;
      result = result && (hasText() == other.hasText());
      if (hasText()) {
        result = result && getText()
            .equals(other.getText());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGoalId()) {
        hash = (37 * hash) + GOAL_ID_FIELD_NUMBER;
        hash = (53 * hash) + getGoalId().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static choreo.Action.GoalStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.Action.GoalStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.Action.GoalStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(choreo.Action.GoalStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code choreo.GoalStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:choreo.GoalStatus)
        choreo.Action.GoalStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return choreo.Action.internal_static_choreo_GoalStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return choreo.Action.internal_static_choreo_GoalStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                choreo.Action.GoalStatus.class, choreo.Action.GoalStatus.Builder.class);
      }

      // Construct using choreo.Action.GoalStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (goalIdBuilder_ == null) {
          goalId_ = null;
        } else {
          goalId_ = null;
          goalIdBuilder_ = null;
        }
        status_ = 0;

        if (textBuilder_ == null) {
          text_ = null;
        } else {
          text_ = null;
          textBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return choreo.Action.internal_static_choreo_GoalStatus_descriptor;
      }

      public choreo.Action.GoalStatus getDefaultInstanceForType() {
        return choreo.Action.GoalStatus.getDefaultInstance();
      }

      public choreo.Action.GoalStatus build() {
        choreo.Action.GoalStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public choreo.Action.GoalStatus buildPartial() {
        choreo.Action.GoalStatus result = new choreo.Action.GoalStatus(this);
        if (goalIdBuilder_ == null) {
          result.goalId_ = goalId_;
        } else {
          result.goalId_ = goalIdBuilder_.build();
        }
        result.status_ = status_;
        if (textBuilder_ == null) {
          result.text_ = text_;
        } else {
          result.text_ = textBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof choreo.Action.GoalStatus) {
          return mergeFrom((choreo.Action.GoalStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(choreo.Action.GoalStatus other) {
        if (other == choreo.Action.GoalStatus.getDefaultInstance()) return this;
        if (other.hasGoalId()) {
          mergeGoalId(other.getGoalId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.hasText()) {
          mergeText(other.getText());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        choreo.Action.GoalStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (choreo.Action.GoalStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private choreo.Action.GoalID goalId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.Action.GoalID, choreo.Action.GoalID.Builder, choreo.Action.GoalIDOrBuilder> goalIdBuilder_;
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public boolean hasGoalId() {
        return goalIdBuilder_ != null || goalId_ != null;
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public choreo.Action.GoalID getGoalId() {
        if (goalIdBuilder_ == null) {
          return goalId_ == null ? choreo.Action.GoalID.getDefaultInstance() : goalId_;
        } else {
          return goalIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public Builder setGoalId(choreo.Action.GoalID value) {
        if (goalIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          goalId_ = value;
          onChanged();
        } else {
          goalIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public Builder setGoalId(
          choreo.Action.GoalID.Builder builderForValue) {
        if (goalIdBuilder_ == null) {
          goalId_ = builderForValue.build();
          onChanged();
        } else {
          goalIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public Builder mergeGoalId(choreo.Action.GoalID value) {
        if (goalIdBuilder_ == null) {
          if (goalId_ != null) {
            goalId_ =
              choreo.Action.GoalID.newBuilder(goalId_).mergeFrom(value).buildPartial();
          } else {
            goalId_ = value;
          }
          onChanged();
        } else {
          goalIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public Builder clearGoalId() {
        if (goalIdBuilder_ == null) {
          goalId_ = null;
          onChanged();
        } else {
          goalId_ = null;
          goalIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public choreo.Action.GoalID.Builder getGoalIdBuilder() {
        
        onChanged();
        return getGoalIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      public choreo.Action.GoalIDOrBuilder getGoalIdOrBuilder() {
        if (goalIdBuilder_ != null) {
          return goalIdBuilder_.getMessageOrBuilder();
        } else {
          return goalId_ == null ?
              choreo.Action.GoalID.getDefaultInstance() : goalId_;
        }
      }
      /**
       * <code>.choreo.GoalID goal_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.Action.GoalID, choreo.Action.GoalID.Builder, choreo.Action.GoalIDOrBuilder> 
          getGoalIdFieldBuilder() {
        if (goalIdBuilder_ == null) {
          goalIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.Action.GoalID, choreo.Action.GoalID.Builder, choreo.Action.GoalIDOrBuilder>(
                  getGoalId(),
                  getParentForChildren(),
                  isClean());
          goalId_ = null;
        }
        return goalIdBuilder_;
      }

      private int status_ = 0;
      /**
       * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
       */
      public choreo.Action.GoalStatus.GoalStatusType getStatus() {
        choreo.Action.GoalStatus.GoalStatusType result = choreo.Action.GoalStatus.GoalStatusType.valueOf(status_);
        return result == null ? choreo.Action.GoalStatus.GoalStatusType.UNRECOGNIZED : result;
      }
      /**
       * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
       */
      public Builder setStatus(choreo.Action.GoalStatus.GoalStatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.choreo.GoalStatus.GoalStatusType status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private choreo.StringOuterClass.String text_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.StringOuterClass.String, choreo.StringOuterClass.String.Builder, choreo.StringOuterClass.StringOrBuilder> textBuilder_;
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public boolean hasText() {
        return textBuilder_ != null || text_ != null;
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public choreo.StringOuterClass.String getText() {
        if (textBuilder_ == null) {
          return text_ == null ? choreo.StringOuterClass.String.getDefaultInstance() : text_;
        } else {
          return textBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public Builder setText(choreo.StringOuterClass.String value) {
        if (textBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          text_ = value;
          onChanged();
        } else {
          textBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public Builder setText(
          choreo.StringOuterClass.String.Builder builderForValue) {
        if (textBuilder_ == null) {
          text_ = builderForValue.build();
          onChanged();
        } else {
          textBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public Builder mergeText(choreo.StringOuterClass.String value) {
        if (textBuilder_ == null) {
          if (text_ != null) {
            text_ =
              choreo.StringOuterClass.String.newBuilder(text_).mergeFrom(value).buildPartial();
          } else {
            text_ = value;
          }
          onChanged();
        } else {
          textBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public Builder clearText() {
        if (textBuilder_ == null) {
          text_ = null;
          onChanged();
        } else {
          text_ = null;
          textBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public choreo.StringOuterClass.String.Builder getTextBuilder() {
        
        onChanged();
        return getTextFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      public choreo.StringOuterClass.StringOrBuilder getTextOrBuilder() {
        if (textBuilder_ != null) {
          return textBuilder_.getMessageOrBuilder();
        } else {
          return text_ == null ?
              choreo.StringOuterClass.String.getDefaultInstance() : text_;
        }
      }
      /**
       * <code>.choreo.String text = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.StringOuterClass.String, choreo.StringOuterClass.String.Builder, choreo.StringOuterClass.StringOrBuilder> 
          getTextFieldBuilder() {
        if (textBuilder_ == null) {
          textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.StringOuterClass.String, choreo.StringOuterClass.String.Builder, choreo.StringOuterClass.StringOrBuilder>(
                  getText(),
                  getParentForChildren(),
                  isClean());
          text_ = null;
        }
        return textBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:choreo.GoalStatus)
    }

    // @@protoc_insertion_point(class_scope:choreo.GoalStatus)
    private static final choreo.Action.GoalStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new choreo.Action.GoalStatus();
    }

    public static choreo.Action.GoalStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoalStatus>
        PARSER = new com.google.protobuf.AbstractParser<GoalStatus>() {
      public GoalStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GoalStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoalStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoalStatus> getParserForType() {
      return PARSER;
    }

    public choreo.Action.GoalStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GoalStatusArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:choreo.GoalStatusArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.choreo.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    choreo.HeaderOuterClass.Header getHeader();
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    java.util.List<choreo.Action.GoalStatus> 
        getStatusListList();
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    choreo.Action.GoalStatus getStatusList(int index);
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    int getStatusListCount();
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    java.util.List<? extends choreo.Action.GoalStatusOrBuilder> 
        getStatusListOrBuilderList();
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    choreo.Action.GoalStatusOrBuilder getStatusListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code choreo.GoalStatusArray}
   */
  public  static final class GoalStatusArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:choreo.GoalStatusArray)
      GoalStatusArrayOrBuilder {
    // Use GoalStatusArray.newBuilder() to construct.
    private GoalStatusArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoalStatusArray() {
      statusList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GoalStatusArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              choreo.HeaderOuterClass.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(choreo.HeaderOuterClass.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                statusList_ = new java.util.ArrayList<choreo.Action.GoalStatus>();
                mutable_bitField0_ |= 0x00000002;
              }
              statusList_.add(
                  input.readMessage(choreo.Action.GoalStatus.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          statusList_ = java.util.Collections.unmodifiableList(statusList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return choreo.Action.internal_static_choreo_GoalStatusArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return choreo.Action.internal_static_choreo_GoalStatusArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              choreo.Action.GoalStatusArray.class, choreo.Action.GoalStatusArray.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private choreo.HeaderOuterClass.Header header_;
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public choreo.HeaderOuterClass.Header getHeader() {
      return header_ == null ? choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int STATUS_LIST_FIELD_NUMBER = 2;
    private java.util.List<choreo.Action.GoalStatus> statusList_;
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    public java.util.List<choreo.Action.GoalStatus> getStatusListList() {
      return statusList_;
    }
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    public java.util.List<? extends choreo.Action.GoalStatusOrBuilder> 
        getStatusListOrBuilderList() {
      return statusList_;
    }
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    public int getStatusListCount() {
      return statusList_.size();
    }
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    public choreo.Action.GoalStatus getStatusList(int index) {
      return statusList_.get(index);
    }
    /**
     * <code>repeated .choreo.GoalStatus status_list = 2;</code>
     */
    public choreo.Action.GoalStatusOrBuilder getStatusListOrBuilder(
        int index) {
      return statusList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      for (int i = 0; i < statusList_.size(); i++) {
        output.writeMessage(2, statusList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      for (int i = 0; i < statusList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, statusList_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof choreo.Action.GoalStatusArray)) {
        return super.equals(obj);
      }
      choreo.Action.GoalStatusArray other = (choreo.Action.GoalStatusArray) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getStatusListList()
          .equals(other.getStatusListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (getStatusListCount() > 0) {
        hash = (37 * hash) + STATUS_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getStatusListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static choreo.Action.GoalStatusArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalStatusArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalStatusArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalStatusArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalStatusArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.Action.GoalStatusArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.Action.GoalStatusArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalStatusArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.Action.GoalStatusArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalStatusArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.Action.GoalStatusArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.Action.GoalStatusArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(choreo.Action.GoalStatusArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code choreo.GoalStatusArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:choreo.GoalStatusArray)
        choreo.Action.GoalStatusArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return choreo.Action.internal_static_choreo_GoalStatusArray_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return choreo.Action.internal_static_choreo_GoalStatusArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                choreo.Action.GoalStatusArray.class, choreo.Action.GoalStatusArray.Builder.class);
      }

      // Construct using choreo.Action.GoalStatusArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStatusListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (statusListBuilder_ == null) {
          statusList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          statusListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return choreo.Action.internal_static_choreo_GoalStatusArray_descriptor;
      }

      public choreo.Action.GoalStatusArray getDefaultInstanceForType() {
        return choreo.Action.GoalStatusArray.getDefaultInstance();
      }

      public choreo.Action.GoalStatusArray build() {
        choreo.Action.GoalStatusArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public choreo.Action.GoalStatusArray buildPartial() {
        choreo.Action.GoalStatusArray result = new choreo.Action.GoalStatusArray(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (statusListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            statusList_ = java.util.Collections.unmodifiableList(statusList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.statusList_ = statusList_;
        } else {
          result.statusList_ = statusListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof choreo.Action.GoalStatusArray) {
          return mergeFrom((choreo.Action.GoalStatusArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(choreo.Action.GoalStatusArray other) {
        if (other == choreo.Action.GoalStatusArray.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (statusListBuilder_ == null) {
          if (!other.statusList_.isEmpty()) {
            if (statusList_.isEmpty()) {
              statusList_ = other.statusList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStatusListIsMutable();
              statusList_.addAll(other.statusList_);
            }
            onChanged();
          }
        } else {
          if (!other.statusList_.isEmpty()) {
            if (statusListBuilder_.isEmpty()) {
              statusListBuilder_.dispose();
              statusListBuilder_ = null;
              statusList_ = other.statusList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              statusListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStatusListFieldBuilder() : null;
            } else {
              statusListBuilder_.addAllMessages(other.statusList_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        choreo.Action.GoalStatusArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (choreo.Action.GoalStatusArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private choreo.HeaderOuterClass.Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder setHeader(choreo.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder setHeader(
          choreo.HeaderOuterClass.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder mergeHeader(choreo.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              choreo.HeaderOuterClass.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.util.List<choreo.Action.GoalStatus> statusList_ =
        java.util.Collections.emptyList();
      private void ensureStatusListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          statusList_ = new java.util.ArrayList<choreo.Action.GoalStatus>(statusList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          choreo.Action.GoalStatus, choreo.Action.GoalStatus.Builder, choreo.Action.GoalStatusOrBuilder> statusListBuilder_;

      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public java.util.List<choreo.Action.GoalStatus> getStatusListList() {
        if (statusListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(statusList_);
        } else {
          return statusListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public int getStatusListCount() {
        if (statusListBuilder_ == null) {
          return statusList_.size();
        } else {
          return statusListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public choreo.Action.GoalStatus getStatusList(int index) {
        if (statusListBuilder_ == null) {
          return statusList_.get(index);
        } else {
          return statusListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder setStatusList(
          int index, choreo.Action.GoalStatus value) {
        if (statusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusListIsMutable();
          statusList_.set(index, value);
          onChanged();
        } else {
          statusListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder setStatusList(
          int index, choreo.Action.GoalStatus.Builder builderForValue) {
        if (statusListBuilder_ == null) {
          ensureStatusListIsMutable();
          statusList_.set(index, builderForValue.build());
          onChanged();
        } else {
          statusListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder addStatusList(choreo.Action.GoalStatus value) {
        if (statusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusListIsMutable();
          statusList_.add(value);
          onChanged();
        } else {
          statusListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder addStatusList(
          int index, choreo.Action.GoalStatus value) {
        if (statusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusListIsMutable();
          statusList_.add(index, value);
          onChanged();
        } else {
          statusListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder addStatusList(
          choreo.Action.GoalStatus.Builder builderForValue) {
        if (statusListBuilder_ == null) {
          ensureStatusListIsMutable();
          statusList_.add(builderForValue.build());
          onChanged();
        } else {
          statusListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder addStatusList(
          int index, choreo.Action.GoalStatus.Builder builderForValue) {
        if (statusListBuilder_ == null) {
          ensureStatusListIsMutable();
          statusList_.add(index, builderForValue.build());
          onChanged();
        } else {
          statusListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder addAllStatusList(
          java.lang.Iterable<? extends choreo.Action.GoalStatus> values) {
        if (statusListBuilder_ == null) {
          ensureStatusListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, statusList_);
          onChanged();
        } else {
          statusListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder clearStatusList() {
        if (statusListBuilder_ == null) {
          statusList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          statusListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public Builder removeStatusList(int index) {
        if (statusListBuilder_ == null) {
          ensureStatusListIsMutable();
          statusList_.remove(index);
          onChanged();
        } else {
          statusListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public choreo.Action.GoalStatus.Builder getStatusListBuilder(
          int index) {
        return getStatusListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public choreo.Action.GoalStatusOrBuilder getStatusListOrBuilder(
          int index) {
        if (statusListBuilder_ == null) {
          return statusList_.get(index);  } else {
          return statusListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public java.util.List<? extends choreo.Action.GoalStatusOrBuilder> 
           getStatusListOrBuilderList() {
        if (statusListBuilder_ != null) {
          return statusListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(statusList_);
        }
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public choreo.Action.GoalStatus.Builder addStatusListBuilder() {
        return getStatusListFieldBuilder().addBuilder(
            choreo.Action.GoalStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public choreo.Action.GoalStatus.Builder addStatusListBuilder(
          int index) {
        return getStatusListFieldBuilder().addBuilder(
            index, choreo.Action.GoalStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .choreo.GoalStatus status_list = 2;</code>
       */
      public java.util.List<choreo.Action.GoalStatus.Builder> 
           getStatusListBuilderList() {
        return getStatusListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          choreo.Action.GoalStatus, choreo.Action.GoalStatus.Builder, choreo.Action.GoalStatusOrBuilder> 
          getStatusListFieldBuilder() {
        if (statusListBuilder_ == null) {
          statusListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              choreo.Action.GoalStatus, choreo.Action.GoalStatus.Builder, choreo.Action.GoalStatusOrBuilder>(
                  statusList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          statusList_ = null;
        }
        return statusListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:choreo.GoalStatusArray)
    }

    // @@protoc_insertion_point(class_scope:choreo.GoalStatusArray)
    private static final choreo.Action.GoalStatusArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new choreo.Action.GoalStatusArray();
    }

    public static choreo.Action.GoalStatusArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoalStatusArray>
        PARSER = new com.google.protobuf.AbstractParser<GoalStatusArray>() {
      public GoalStatusArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GoalStatusArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoalStatusArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoalStatusArray> getParserForType() {
      return PARSER;
    }

    public choreo.Action.GoalStatusArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_choreo_GoalID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_choreo_GoalID_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_choreo_GoalStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_choreo_GoalStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_choreo_GoalStatusArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_choreo_GoalStatusArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023action/action.proto\022\006choreo\032\037google/pr" +
      "otobuf/timestamp.proto\032\026primitive/header" +
      ".proto\032\026primitive/string.proto\"O\n\006GoalID" +
      "\022)\n\005stamp\030\001 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\032\n\002id\030\002 \001(\0132\016.choreo.String\"\232\002\n\nGoal" +
      "Status\022\037\n\007goal_id\030\001 \001(\0132\016.choreo.GoalID\022" +
      "1\n\006status\030\002 \001(\0162!.choreo.GoalStatus.Goal" +
      "StatusType\022\034\n\004text\030\003 \001(\0132\016.choreo.String" +
      "\"\231\001\n\016GoalStatusType\022\013\n\007PENDING\020\000\022\n\n\006ACTI" +
      "VE\020\001\022\r\n\tPREEMPTED\020\002\022\r\n\tSUCCEEDED\020\003\022\013\n\007AB",
      "ORTED\020\004\022\014\n\010REJECTED\020\005\022\016\n\nPREEMPTING\020\006\022\r\n" +
      "\tRECALLING\020\007\022\014\n\010RECALLED\020\010\022\010\n\004LOST\020\t\"Z\n\017" +
      "GoalStatusArray\022\036\n\006header\030\001 \001(\0132\016.choreo" +
      ".Header\022\'\n\013status_list\030\002 \003(\0132\022.choreo.Go" +
      "alStatusb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          choreo.HeaderOuterClass.getDescriptor(),
          choreo.StringOuterClass.getDescriptor(),
        }, assigner);
    internal_static_choreo_GoalID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_choreo_GoalID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_choreo_GoalID_descriptor,
        new java.lang.String[] { "Stamp", "Id", });
    internal_static_choreo_GoalStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_choreo_GoalStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_choreo_GoalStatus_descriptor,
        new java.lang.String[] { "GoalId", "Status", "Text", });
    internal_static_choreo_GoalStatusArray_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_choreo_GoalStatusArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_choreo_GoalStatusArray_descriptor,
        new java.lang.String[] { "Header", "StatusList", });
    com.google.protobuf.TimestampProto.getDescriptor();
    choreo.HeaderOuterClass.getDescriptor();
    choreo.StringOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
