// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geometric/inertia.proto

package choreo;

public final class InertiaOuterClass {
  private InertiaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InertiaStampedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:choreo.InertiaStamped)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.choreo.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    choreo.HeaderOuterClass.Header getHeader();
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.choreo.Inertia inertia = 2;</code>
     */
    boolean hasInertia();
    /**
     * <code>.choreo.Inertia inertia = 2;</code>
     */
    choreo.InertiaOuterClass.Inertia getInertia();
    /**
     * <code>.choreo.Inertia inertia = 2;</code>
     */
    choreo.InertiaOuterClass.InertiaOrBuilder getInertiaOrBuilder();
  }
  /**
   * Protobuf type {@code choreo.InertiaStamped}
   */
  public  static final class InertiaStamped extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:choreo.InertiaStamped)
      InertiaStampedOrBuilder {
    // Use InertiaStamped.newBuilder() to construct.
    private InertiaStamped(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InertiaStamped() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InertiaStamped(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              choreo.HeaderOuterClass.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(choreo.HeaderOuterClass.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              choreo.InertiaOuterClass.Inertia.Builder subBuilder = null;
              if (inertia_ != null) {
                subBuilder = inertia_.toBuilder();
              }
              inertia_ = input.readMessage(choreo.InertiaOuterClass.Inertia.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(inertia_);
                inertia_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return choreo.InertiaOuterClass.internal_static_choreo_InertiaStamped_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return choreo.InertiaOuterClass.internal_static_choreo_InertiaStamped_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              choreo.InertiaOuterClass.InertiaStamped.class, choreo.InertiaOuterClass.InertiaStamped.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private choreo.HeaderOuterClass.Header header_;
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public choreo.HeaderOuterClass.Header getHeader() {
      return header_ == null ? choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int INERTIA_FIELD_NUMBER = 2;
    private choreo.InertiaOuterClass.Inertia inertia_;
    /**
     * <code>.choreo.Inertia inertia = 2;</code>
     */
    public boolean hasInertia() {
      return inertia_ != null;
    }
    /**
     * <code>.choreo.Inertia inertia = 2;</code>
     */
    public choreo.InertiaOuterClass.Inertia getInertia() {
      return inertia_ == null ? choreo.InertiaOuterClass.Inertia.getDefaultInstance() : inertia_;
    }
    /**
     * <code>.choreo.Inertia inertia = 2;</code>
     */
    public choreo.InertiaOuterClass.InertiaOrBuilder getInertiaOrBuilder() {
      return getInertia();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (inertia_ != null) {
        output.writeMessage(2, getInertia());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (inertia_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getInertia());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof choreo.InertiaOuterClass.InertiaStamped)) {
        return super.equals(obj);
      }
      choreo.InertiaOuterClass.InertiaStamped other = (choreo.InertiaOuterClass.InertiaStamped) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasInertia() == other.hasInertia());
      if (hasInertia()) {
        result = result && getInertia()
            .equals(other.getInertia());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasInertia()) {
        hash = (37 * hash) + INERTIA_FIELD_NUMBER;
        hash = (53 * hash) + getInertia().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.InertiaOuterClass.InertiaStamped parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(choreo.InertiaOuterClass.InertiaStamped prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code choreo.InertiaStamped}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:choreo.InertiaStamped)
        choreo.InertiaOuterClass.InertiaStampedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return choreo.InertiaOuterClass.internal_static_choreo_InertiaStamped_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return choreo.InertiaOuterClass.internal_static_choreo_InertiaStamped_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                choreo.InertiaOuterClass.InertiaStamped.class, choreo.InertiaOuterClass.InertiaStamped.Builder.class);
      }

      // Construct using choreo.InertiaOuterClass.InertiaStamped.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (inertiaBuilder_ == null) {
          inertia_ = null;
        } else {
          inertia_ = null;
          inertiaBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return choreo.InertiaOuterClass.internal_static_choreo_InertiaStamped_descriptor;
      }

      public choreo.InertiaOuterClass.InertiaStamped getDefaultInstanceForType() {
        return choreo.InertiaOuterClass.InertiaStamped.getDefaultInstance();
      }

      public choreo.InertiaOuterClass.InertiaStamped build() {
        choreo.InertiaOuterClass.InertiaStamped result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public choreo.InertiaOuterClass.InertiaStamped buildPartial() {
        choreo.InertiaOuterClass.InertiaStamped result = new choreo.InertiaOuterClass.InertiaStamped(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (inertiaBuilder_ == null) {
          result.inertia_ = inertia_;
        } else {
          result.inertia_ = inertiaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof choreo.InertiaOuterClass.InertiaStamped) {
          return mergeFrom((choreo.InertiaOuterClass.InertiaStamped)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(choreo.InertiaOuterClass.InertiaStamped other) {
        if (other == choreo.InertiaOuterClass.InertiaStamped.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasInertia()) {
          mergeInertia(other.getInertia());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        choreo.InertiaOuterClass.InertiaStamped parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (choreo.InertiaOuterClass.InertiaStamped) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private choreo.HeaderOuterClass.Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder setHeader(choreo.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder setHeader(
          choreo.HeaderOuterClass.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder mergeHeader(choreo.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              choreo.HeaderOuterClass.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private choreo.InertiaOuterClass.Inertia inertia_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.InertiaOuterClass.Inertia, choreo.InertiaOuterClass.Inertia.Builder, choreo.InertiaOuterClass.InertiaOrBuilder> inertiaBuilder_;
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public boolean hasInertia() {
        return inertiaBuilder_ != null || inertia_ != null;
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public choreo.InertiaOuterClass.Inertia getInertia() {
        if (inertiaBuilder_ == null) {
          return inertia_ == null ? choreo.InertiaOuterClass.Inertia.getDefaultInstance() : inertia_;
        } else {
          return inertiaBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public Builder setInertia(choreo.InertiaOuterClass.Inertia value) {
        if (inertiaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inertia_ = value;
          onChanged();
        } else {
          inertiaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public Builder setInertia(
          choreo.InertiaOuterClass.Inertia.Builder builderForValue) {
        if (inertiaBuilder_ == null) {
          inertia_ = builderForValue.build();
          onChanged();
        } else {
          inertiaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public Builder mergeInertia(choreo.InertiaOuterClass.Inertia value) {
        if (inertiaBuilder_ == null) {
          if (inertia_ != null) {
            inertia_ =
              choreo.InertiaOuterClass.Inertia.newBuilder(inertia_).mergeFrom(value).buildPartial();
          } else {
            inertia_ = value;
          }
          onChanged();
        } else {
          inertiaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public Builder clearInertia() {
        if (inertiaBuilder_ == null) {
          inertia_ = null;
          onChanged();
        } else {
          inertia_ = null;
          inertiaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public choreo.InertiaOuterClass.Inertia.Builder getInertiaBuilder() {
        
        onChanged();
        return getInertiaFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      public choreo.InertiaOuterClass.InertiaOrBuilder getInertiaOrBuilder() {
        if (inertiaBuilder_ != null) {
          return inertiaBuilder_.getMessageOrBuilder();
        } else {
          return inertia_ == null ?
              choreo.InertiaOuterClass.Inertia.getDefaultInstance() : inertia_;
        }
      }
      /**
       * <code>.choreo.Inertia inertia = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.InertiaOuterClass.Inertia, choreo.InertiaOuterClass.Inertia.Builder, choreo.InertiaOuterClass.InertiaOrBuilder> 
          getInertiaFieldBuilder() {
        if (inertiaBuilder_ == null) {
          inertiaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.InertiaOuterClass.Inertia, choreo.InertiaOuterClass.Inertia.Builder, choreo.InertiaOuterClass.InertiaOrBuilder>(
                  getInertia(),
                  getParentForChildren(),
                  isClean());
          inertia_ = null;
        }
        return inertiaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:choreo.InertiaStamped)
    }

    // @@protoc_insertion_point(class_scope:choreo.InertiaStamped)
    private static final choreo.InertiaOuterClass.InertiaStamped DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new choreo.InertiaOuterClass.InertiaStamped();
    }

    public static choreo.InertiaOuterClass.InertiaStamped getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InertiaStamped>
        PARSER = new com.google.protobuf.AbstractParser<InertiaStamped>() {
      public InertiaStamped parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InertiaStamped(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InertiaStamped> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InertiaStamped> getParserForType() {
      return PARSER;
    }

    public choreo.InertiaOuterClass.InertiaStamped getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InertiaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:choreo.Inertia)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.choreo.Float64 m = 1;</code>
     */
    boolean hasM();
    /**
     * <code>.choreo.Float64 m = 1;</code>
     */
    choreo.FloatOuterClass.Float64 getM();
    /**
     * <code>.choreo.Float64 m = 1;</code>
     */
    choreo.FloatOuterClass.Float64OrBuilder getMOrBuilder();

    /**
     * <code>.choreo.Vector3 com = 2;</code>
     */
    boolean hasCom();
    /**
     * <code>.choreo.Vector3 com = 2;</code>
     */
    choreo.Vector.Vector3 getCom();
    /**
     * <code>.choreo.Vector3 com = 2;</code>
     */
    choreo.Vector.Vector3OrBuilder getComOrBuilder();

    /**
     * <code>.choreo.Float64 ixx = 3;</code>
     */
    boolean hasIxx();
    /**
     * <code>.choreo.Float64 ixx = 3;</code>
     */
    choreo.FloatOuterClass.Float64 getIxx();
    /**
     * <code>.choreo.Float64 ixx = 3;</code>
     */
    choreo.FloatOuterClass.Float64OrBuilder getIxxOrBuilder();

    /**
     * <code>.choreo.Float64 ixy = 4;</code>
     */
    boolean hasIxy();
    /**
     * <code>.choreo.Float64 ixy = 4;</code>
     */
    choreo.FloatOuterClass.Float64 getIxy();
    /**
     * <code>.choreo.Float64 ixy = 4;</code>
     */
    choreo.FloatOuterClass.Float64OrBuilder getIxyOrBuilder();

    /**
     * <code>.choreo.Float64 ixz = 5;</code>
     */
    boolean hasIxz();
    /**
     * <code>.choreo.Float64 ixz = 5;</code>
     */
    choreo.FloatOuterClass.Float64 getIxz();
    /**
     * <code>.choreo.Float64 ixz = 5;</code>
     */
    choreo.FloatOuterClass.Float64OrBuilder getIxzOrBuilder();

    /**
     * <code>.choreo.Float64 iyy = 7;</code>
     */
    boolean hasIyy();
    /**
     * <code>.choreo.Float64 iyy = 7;</code>
     */
    choreo.FloatOuterClass.Float64 getIyy();
    /**
     * <code>.choreo.Float64 iyy = 7;</code>
     */
    choreo.FloatOuterClass.Float64OrBuilder getIyyOrBuilder();

    /**
     * <code>.choreo.Float64 iyz = 8;</code>
     */
    boolean hasIyz();
    /**
     * <code>.choreo.Float64 iyz = 8;</code>
     */
    choreo.FloatOuterClass.Float64 getIyz();
    /**
     * <code>.choreo.Float64 iyz = 8;</code>
     */
    choreo.FloatOuterClass.Float64OrBuilder getIyzOrBuilder();

    /**
     * <code>.choreo.Float64 izz = 6;</code>
     */
    boolean hasIzz();
    /**
     * <code>.choreo.Float64 izz = 6;</code>
     */
    choreo.FloatOuterClass.Float64 getIzz();
    /**
     * <code>.choreo.Float64 izz = 6;</code>
     */
    choreo.FloatOuterClass.Float64OrBuilder getIzzOrBuilder();
  }
  /**
   * Protobuf type {@code choreo.Inertia}
   */
  public  static final class Inertia extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:choreo.Inertia)
      InertiaOrBuilder {
    // Use Inertia.newBuilder() to construct.
    private Inertia(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Inertia() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Inertia(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              choreo.FloatOuterClass.Float64.Builder subBuilder = null;
              if (m_ != null) {
                subBuilder = m_.toBuilder();
              }
              m_ = input.readMessage(choreo.FloatOuterClass.Float64.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(m_);
                m_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              choreo.Vector.Vector3.Builder subBuilder = null;
              if (com_ != null) {
                subBuilder = com_.toBuilder();
              }
              com_ = input.readMessage(choreo.Vector.Vector3.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(com_);
                com_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              choreo.FloatOuterClass.Float64.Builder subBuilder = null;
              if (ixx_ != null) {
                subBuilder = ixx_.toBuilder();
              }
              ixx_ = input.readMessage(choreo.FloatOuterClass.Float64.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ixx_);
                ixx_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              choreo.FloatOuterClass.Float64.Builder subBuilder = null;
              if (ixy_ != null) {
                subBuilder = ixy_.toBuilder();
              }
              ixy_ = input.readMessage(choreo.FloatOuterClass.Float64.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ixy_);
                ixy_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              choreo.FloatOuterClass.Float64.Builder subBuilder = null;
              if (ixz_ != null) {
                subBuilder = ixz_.toBuilder();
              }
              ixz_ = input.readMessage(choreo.FloatOuterClass.Float64.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ixz_);
                ixz_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              choreo.FloatOuterClass.Float64.Builder subBuilder = null;
              if (izz_ != null) {
                subBuilder = izz_.toBuilder();
              }
              izz_ = input.readMessage(choreo.FloatOuterClass.Float64.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(izz_);
                izz_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              choreo.FloatOuterClass.Float64.Builder subBuilder = null;
              if (iyy_ != null) {
                subBuilder = iyy_.toBuilder();
              }
              iyy_ = input.readMessage(choreo.FloatOuterClass.Float64.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(iyy_);
                iyy_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              choreo.FloatOuterClass.Float64.Builder subBuilder = null;
              if (iyz_ != null) {
                subBuilder = iyz_.toBuilder();
              }
              iyz_ = input.readMessage(choreo.FloatOuterClass.Float64.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(iyz_);
                iyz_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return choreo.InertiaOuterClass.internal_static_choreo_Inertia_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return choreo.InertiaOuterClass.internal_static_choreo_Inertia_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              choreo.InertiaOuterClass.Inertia.class, choreo.InertiaOuterClass.Inertia.Builder.class);
    }

    public static final int M_FIELD_NUMBER = 1;
    private choreo.FloatOuterClass.Float64 m_;
    /**
     * <code>.choreo.Float64 m = 1;</code>
     */
    public boolean hasM() {
      return m_ != null;
    }
    /**
     * <code>.choreo.Float64 m = 1;</code>
     */
    public choreo.FloatOuterClass.Float64 getM() {
      return m_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : m_;
    }
    /**
     * <code>.choreo.Float64 m = 1;</code>
     */
    public choreo.FloatOuterClass.Float64OrBuilder getMOrBuilder() {
      return getM();
    }

    public static final int COM_FIELD_NUMBER = 2;
    private choreo.Vector.Vector3 com_;
    /**
     * <code>.choreo.Vector3 com = 2;</code>
     */
    public boolean hasCom() {
      return com_ != null;
    }
    /**
     * <code>.choreo.Vector3 com = 2;</code>
     */
    public choreo.Vector.Vector3 getCom() {
      return com_ == null ? choreo.Vector.Vector3.getDefaultInstance() : com_;
    }
    /**
     * <code>.choreo.Vector3 com = 2;</code>
     */
    public choreo.Vector.Vector3OrBuilder getComOrBuilder() {
      return getCom();
    }

    public static final int IXX_FIELD_NUMBER = 3;
    private choreo.FloatOuterClass.Float64 ixx_;
    /**
     * <code>.choreo.Float64 ixx = 3;</code>
     */
    public boolean hasIxx() {
      return ixx_ != null;
    }
    /**
     * <code>.choreo.Float64 ixx = 3;</code>
     */
    public choreo.FloatOuterClass.Float64 getIxx() {
      return ixx_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : ixx_;
    }
    /**
     * <code>.choreo.Float64 ixx = 3;</code>
     */
    public choreo.FloatOuterClass.Float64OrBuilder getIxxOrBuilder() {
      return getIxx();
    }

    public static final int IXY_FIELD_NUMBER = 4;
    private choreo.FloatOuterClass.Float64 ixy_;
    /**
     * <code>.choreo.Float64 ixy = 4;</code>
     */
    public boolean hasIxy() {
      return ixy_ != null;
    }
    /**
     * <code>.choreo.Float64 ixy = 4;</code>
     */
    public choreo.FloatOuterClass.Float64 getIxy() {
      return ixy_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : ixy_;
    }
    /**
     * <code>.choreo.Float64 ixy = 4;</code>
     */
    public choreo.FloatOuterClass.Float64OrBuilder getIxyOrBuilder() {
      return getIxy();
    }

    public static final int IXZ_FIELD_NUMBER = 5;
    private choreo.FloatOuterClass.Float64 ixz_;
    /**
     * <code>.choreo.Float64 ixz = 5;</code>
     */
    public boolean hasIxz() {
      return ixz_ != null;
    }
    /**
     * <code>.choreo.Float64 ixz = 5;</code>
     */
    public choreo.FloatOuterClass.Float64 getIxz() {
      return ixz_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : ixz_;
    }
    /**
     * <code>.choreo.Float64 ixz = 5;</code>
     */
    public choreo.FloatOuterClass.Float64OrBuilder getIxzOrBuilder() {
      return getIxz();
    }

    public static final int IYY_FIELD_NUMBER = 7;
    private choreo.FloatOuterClass.Float64 iyy_;
    /**
     * <code>.choreo.Float64 iyy = 7;</code>
     */
    public boolean hasIyy() {
      return iyy_ != null;
    }
    /**
     * <code>.choreo.Float64 iyy = 7;</code>
     */
    public choreo.FloatOuterClass.Float64 getIyy() {
      return iyy_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : iyy_;
    }
    /**
     * <code>.choreo.Float64 iyy = 7;</code>
     */
    public choreo.FloatOuterClass.Float64OrBuilder getIyyOrBuilder() {
      return getIyy();
    }

    public static final int IYZ_FIELD_NUMBER = 8;
    private choreo.FloatOuterClass.Float64 iyz_;
    /**
     * <code>.choreo.Float64 iyz = 8;</code>
     */
    public boolean hasIyz() {
      return iyz_ != null;
    }
    /**
     * <code>.choreo.Float64 iyz = 8;</code>
     */
    public choreo.FloatOuterClass.Float64 getIyz() {
      return iyz_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : iyz_;
    }
    /**
     * <code>.choreo.Float64 iyz = 8;</code>
     */
    public choreo.FloatOuterClass.Float64OrBuilder getIyzOrBuilder() {
      return getIyz();
    }

    public static final int IZZ_FIELD_NUMBER = 6;
    private choreo.FloatOuterClass.Float64 izz_;
    /**
     * <code>.choreo.Float64 izz = 6;</code>
     */
    public boolean hasIzz() {
      return izz_ != null;
    }
    /**
     * <code>.choreo.Float64 izz = 6;</code>
     */
    public choreo.FloatOuterClass.Float64 getIzz() {
      return izz_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : izz_;
    }
    /**
     * <code>.choreo.Float64 izz = 6;</code>
     */
    public choreo.FloatOuterClass.Float64OrBuilder getIzzOrBuilder() {
      return getIzz();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (m_ != null) {
        output.writeMessage(1, getM());
      }
      if (com_ != null) {
        output.writeMessage(2, getCom());
      }
      if (ixx_ != null) {
        output.writeMessage(3, getIxx());
      }
      if (ixy_ != null) {
        output.writeMessage(4, getIxy());
      }
      if (ixz_ != null) {
        output.writeMessage(5, getIxz());
      }
      if (izz_ != null) {
        output.writeMessage(6, getIzz());
      }
      if (iyy_ != null) {
        output.writeMessage(7, getIyy());
      }
      if (iyz_ != null) {
        output.writeMessage(8, getIyz());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (m_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getM());
      }
      if (com_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCom());
      }
      if (ixx_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getIxx());
      }
      if (ixy_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getIxy());
      }
      if (ixz_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getIxz());
      }
      if (izz_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getIzz());
      }
      if (iyy_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getIyy());
      }
      if (iyz_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getIyz());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof choreo.InertiaOuterClass.Inertia)) {
        return super.equals(obj);
      }
      choreo.InertiaOuterClass.Inertia other = (choreo.InertiaOuterClass.Inertia) obj;

      boolean result = true;
      result = result && (hasM() == other.hasM());
      if (hasM()) {
        result = result && getM()
            .equals(other.getM());
      }
      result = result && (hasCom() == other.hasCom());
      if (hasCom()) {
        result = result && getCom()
            .equals(other.getCom());
      }
      result = result && (hasIxx() == other.hasIxx());
      if (hasIxx()) {
        result = result && getIxx()
            .equals(other.getIxx());
      }
      result = result && (hasIxy() == other.hasIxy());
      if (hasIxy()) {
        result = result && getIxy()
            .equals(other.getIxy());
      }
      result = result && (hasIxz() == other.hasIxz());
      if (hasIxz()) {
        result = result && getIxz()
            .equals(other.getIxz());
      }
      result = result && (hasIyy() == other.hasIyy());
      if (hasIyy()) {
        result = result && getIyy()
            .equals(other.getIyy());
      }
      result = result && (hasIyz() == other.hasIyz());
      if (hasIyz()) {
        result = result && getIyz()
            .equals(other.getIyz());
      }
      result = result && (hasIzz() == other.hasIzz());
      if (hasIzz()) {
        result = result && getIzz()
            .equals(other.getIzz());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasM()) {
        hash = (37 * hash) + M_FIELD_NUMBER;
        hash = (53 * hash) + getM().hashCode();
      }
      if (hasCom()) {
        hash = (37 * hash) + COM_FIELD_NUMBER;
        hash = (53 * hash) + getCom().hashCode();
      }
      if (hasIxx()) {
        hash = (37 * hash) + IXX_FIELD_NUMBER;
        hash = (53 * hash) + getIxx().hashCode();
      }
      if (hasIxy()) {
        hash = (37 * hash) + IXY_FIELD_NUMBER;
        hash = (53 * hash) + getIxy().hashCode();
      }
      if (hasIxz()) {
        hash = (37 * hash) + IXZ_FIELD_NUMBER;
        hash = (53 * hash) + getIxz().hashCode();
      }
      if (hasIyy()) {
        hash = (37 * hash) + IYY_FIELD_NUMBER;
        hash = (53 * hash) + getIyy().hashCode();
      }
      if (hasIyz()) {
        hash = (37 * hash) + IYZ_FIELD_NUMBER;
        hash = (53 * hash) + getIyz().hashCode();
      }
      if (hasIzz()) {
        hash = (37 * hash) + IZZ_FIELD_NUMBER;
        hash = (53 * hash) + getIzz().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static choreo.InertiaOuterClass.Inertia parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.Inertia parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static choreo.InertiaOuterClass.Inertia parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.InertiaOuterClass.Inertia parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(choreo.InertiaOuterClass.Inertia prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code choreo.Inertia}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:choreo.Inertia)
        choreo.InertiaOuterClass.InertiaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return choreo.InertiaOuterClass.internal_static_choreo_Inertia_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return choreo.InertiaOuterClass.internal_static_choreo_Inertia_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                choreo.InertiaOuterClass.Inertia.class, choreo.InertiaOuterClass.Inertia.Builder.class);
      }

      // Construct using choreo.InertiaOuterClass.Inertia.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (mBuilder_ == null) {
          m_ = null;
        } else {
          m_ = null;
          mBuilder_ = null;
        }
        if (comBuilder_ == null) {
          com_ = null;
        } else {
          com_ = null;
          comBuilder_ = null;
        }
        if (ixxBuilder_ == null) {
          ixx_ = null;
        } else {
          ixx_ = null;
          ixxBuilder_ = null;
        }
        if (ixyBuilder_ == null) {
          ixy_ = null;
        } else {
          ixy_ = null;
          ixyBuilder_ = null;
        }
        if (ixzBuilder_ == null) {
          ixz_ = null;
        } else {
          ixz_ = null;
          ixzBuilder_ = null;
        }
        if (iyyBuilder_ == null) {
          iyy_ = null;
        } else {
          iyy_ = null;
          iyyBuilder_ = null;
        }
        if (iyzBuilder_ == null) {
          iyz_ = null;
        } else {
          iyz_ = null;
          iyzBuilder_ = null;
        }
        if (izzBuilder_ == null) {
          izz_ = null;
        } else {
          izz_ = null;
          izzBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return choreo.InertiaOuterClass.internal_static_choreo_Inertia_descriptor;
      }

      public choreo.InertiaOuterClass.Inertia getDefaultInstanceForType() {
        return choreo.InertiaOuterClass.Inertia.getDefaultInstance();
      }

      public choreo.InertiaOuterClass.Inertia build() {
        choreo.InertiaOuterClass.Inertia result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public choreo.InertiaOuterClass.Inertia buildPartial() {
        choreo.InertiaOuterClass.Inertia result = new choreo.InertiaOuterClass.Inertia(this);
        if (mBuilder_ == null) {
          result.m_ = m_;
        } else {
          result.m_ = mBuilder_.build();
        }
        if (comBuilder_ == null) {
          result.com_ = com_;
        } else {
          result.com_ = comBuilder_.build();
        }
        if (ixxBuilder_ == null) {
          result.ixx_ = ixx_;
        } else {
          result.ixx_ = ixxBuilder_.build();
        }
        if (ixyBuilder_ == null) {
          result.ixy_ = ixy_;
        } else {
          result.ixy_ = ixyBuilder_.build();
        }
        if (ixzBuilder_ == null) {
          result.ixz_ = ixz_;
        } else {
          result.ixz_ = ixzBuilder_.build();
        }
        if (iyyBuilder_ == null) {
          result.iyy_ = iyy_;
        } else {
          result.iyy_ = iyyBuilder_.build();
        }
        if (iyzBuilder_ == null) {
          result.iyz_ = iyz_;
        } else {
          result.iyz_ = iyzBuilder_.build();
        }
        if (izzBuilder_ == null) {
          result.izz_ = izz_;
        } else {
          result.izz_ = izzBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof choreo.InertiaOuterClass.Inertia) {
          return mergeFrom((choreo.InertiaOuterClass.Inertia)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(choreo.InertiaOuterClass.Inertia other) {
        if (other == choreo.InertiaOuterClass.Inertia.getDefaultInstance()) return this;
        if (other.hasM()) {
          mergeM(other.getM());
        }
        if (other.hasCom()) {
          mergeCom(other.getCom());
        }
        if (other.hasIxx()) {
          mergeIxx(other.getIxx());
        }
        if (other.hasIxy()) {
          mergeIxy(other.getIxy());
        }
        if (other.hasIxz()) {
          mergeIxz(other.getIxz());
        }
        if (other.hasIyy()) {
          mergeIyy(other.getIyy());
        }
        if (other.hasIyz()) {
          mergeIyz(other.getIyz());
        }
        if (other.hasIzz()) {
          mergeIzz(other.getIzz());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        choreo.InertiaOuterClass.Inertia parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (choreo.InertiaOuterClass.Inertia) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private choreo.FloatOuterClass.Float64 m_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> mBuilder_;
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public boolean hasM() {
        return mBuilder_ != null || m_ != null;
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public choreo.FloatOuterClass.Float64 getM() {
        if (mBuilder_ == null) {
          return m_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : m_;
        } else {
          return mBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public Builder setM(choreo.FloatOuterClass.Float64 value) {
        if (mBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          m_ = value;
          onChanged();
        } else {
          mBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public Builder setM(
          choreo.FloatOuterClass.Float64.Builder builderForValue) {
        if (mBuilder_ == null) {
          m_ = builderForValue.build();
          onChanged();
        } else {
          mBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public Builder mergeM(choreo.FloatOuterClass.Float64 value) {
        if (mBuilder_ == null) {
          if (m_ != null) {
            m_ =
              choreo.FloatOuterClass.Float64.newBuilder(m_).mergeFrom(value).buildPartial();
          } else {
            m_ = value;
          }
          onChanged();
        } else {
          mBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public Builder clearM() {
        if (mBuilder_ == null) {
          m_ = null;
          onChanged();
        } else {
          m_ = null;
          mBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public choreo.FloatOuterClass.Float64.Builder getMBuilder() {
        
        onChanged();
        return getMFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      public choreo.FloatOuterClass.Float64OrBuilder getMOrBuilder() {
        if (mBuilder_ != null) {
          return mBuilder_.getMessageOrBuilder();
        } else {
          return m_ == null ?
              choreo.FloatOuterClass.Float64.getDefaultInstance() : m_;
        }
      }
      /**
       * <code>.choreo.Float64 m = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> 
          getMFieldBuilder() {
        if (mBuilder_ == null) {
          mBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder>(
                  getM(),
                  getParentForChildren(),
                  isClean());
          m_ = null;
        }
        return mBuilder_;
      }

      private choreo.Vector.Vector3 com_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.Vector.Vector3, choreo.Vector.Vector3.Builder, choreo.Vector.Vector3OrBuilder> comBuilder_;
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public boolean hasCom() {
        return comBuilder_ != null || com_ != null;
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public choreo.Vector.Vector3 getCom() {
        if (comBuilder_ == null) {
          return com_ == null ? choreo.Vector.Vector3.getDefaultInstance() : com_;
        } else {
          return comBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public Builder setCom(choreo.Vector.Vector3 value) {
        if (comBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          com_ = value;
          onChanged();
        } else {
          comBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public Builder setCom(
          choreo.Vector.Vector3.Builder builderForValue) {
        if (comBuilder_ == null) {
          com_ = builderForValue.build();
          onChanged();
        } else {
          comBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public Builder mergeCom(choreo.Vector.Vector3 value) {
        if (comBuilder_ == null) {
          if (com_ != null) {
            com_ =
              choreo.Vector.Vector3.newBuilder(com_).mergeFrom(value).buildPartial();
          } else {
            com_ = value;
          }
          onChanged();
        } else {
          comBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public Builder clearCom() {
        if (comBuilder_ == null) {
          com_ = null;
          onChanged();
        } else {
          com_ = null;
          comBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public choreo.Vector.Vector3.Builder getComBuilder() {
        
        onChanged();
        return getComFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      public choreo.Vector.Vector3OrBuilder getComOrBuilder() {
        if (comBuilder_ != null) {
          return comBuilder_.getMessageOrBuilder();
        } else {
          return com_ == null ?
              choreo.Vector.Vector3.getDefaultInstance() : com_;
        }
      }
      /**
       * <code>.choreo.Vector3 com = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.Vector.Vector3, choreo.Vector.Vector3.Builder, choreo.Vector.Vector3OrBuilder> 
          getComFieldBuilder() {
        if (comBuilder_ == null) {
          comBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.Vector.Vector3, choreo.Vector.Vector3.Builder, choreo.Vector.Vector3OrBuilder>(
                  getCom(),
                  getParentForChildren(),
                  isClean());
          com_ = null;
        }
        return comBuilder_;
      }

      private choreo.FloatOuterClass.Float64 ixx_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> ixxBuilder_;
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public boolean hasIxx() {
        return ixxBuilder_ != null || ixx_ != null;
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public choreo.FloatOuterClass.Float64 getIxx() {
        if (ixxBuilder_ == null) {
          return ixx_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : ixx_;
        } else {
          return ixxBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public Builder setIxx(choreo.FloatOuterClass.Float64 value) {
        if (ixxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ixx_ = value;
          onChanged();
        } else {
          ixxBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public Builder setIxx(
          choreo.FloatOuterClass.Float64.Builder builderForValue) {
        if (ixxBuilder_ == null) {
          ixx_ = builderForValue.build();
          onChanged();
        } else {
          ixxBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public Builder mergeIxx(choreo.FloatOuterClass.Float64 value) {
        if (ixxBuilder_ == null) {
          if (ixx_ != null) {
            ixx_ =
              choreo.FloatOuterClass.Float64.newBuilder(ixx_).mergeFrom(value).buildPartial();
          } else {
            ixx_ = value;
          }
          onChanged();
        } else {
          ixxBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public Builder clearIxx() {
        if (ixxBuilder_ == null) {
          ixx_ = null;
          onChanged();
        } else {
          ixx_ = null;
          ixxBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public choreo.FloatOuterClass.Float64.Builder getIxxBuilder() {
        
        onChanged();
        return getIxxFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      public choreo.FloatOuterClass.Float64OrBuilder getIxxOrBuilder() {
        if (ixxBuilder_ != null) {
          return ixxBuilder_.getMessageOrBuilder();
        } else {
          return ixx_ == null ?
              choreo.FloatOuterClass.Float64.getDefaultInstance() : ixx_;
        }
      }
      /**
       * <code>.choreo.Float64 ixx = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> 
          getIxxFieldBuilder() {
        if (ixxBuilder_ == null) {
          ixxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder>(
                  getIxx(),
                  getParentForChildren(),
                  isClean());
          ixx_ = null;
        }
        return ixxBuilder_;
      }

      private choreo.FloatOuterClass.Float64 ixy_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> ixyBuilder_;
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public boolean hasIxy() {
        return ixyBuilder_ != null || ixy_ != null;
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public choreo.FloatOuterClass.Float64 getIxy() {
        if (ixyBuilder_ == null) {
          return ixy_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : ixy_;
        } else {
          return ixyBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public Builder setIxy(choreo.FloatOuterClass.Float64 value) {
        if (ixyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ixy_ = value;
          onChanged();
        } else {
          ixyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public Builder setIxy(
          choreo.FloatOuterClass.Float64.Builder builderForValue) {
        if (ixyBuilder_ == null) {
          ixy_ = builderForValue.build();
          onChanged();
        } else {
          ixyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public Builder mergeIxy(choreo.FloatOuterClass.Float64 value) {
        if (ixyBuilder_ == null) {
          if (ixy_ != null) {
            ixy_ =
              choreo.FloatOuterClass.Float64.newBuilder(ixy_).mergeFrom(value).buildPartial();
          } else {
            ixy_ = value;
          }
          onChanged();
        } else {
          ixyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public Builder clearIxy() {
        if (ixyBuilder_ == null) {
          ixy_ = null;
          onChanged();
        } else {
          ixy_ = null;
          ixyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public choreo.FloatOuterClass.Float64.Builder getIxyBuilder() {
        
        onChanged();
        return getIxyFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      public choreo.FloatOuterClass.Float64OrBuilder getIxyOrBuilder() {
        if (ixyBuilder_ != null) {
          return ixyBuilder_.getMessageOrBuilder();
        } else {
          return ixy_ == null ?
              choreo.FloatOuterClass.Float64.getDefaultInstance() : ixy_;
        }
      }
      /**
       * <code>.choreo.Float64 ixy = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> 
          getIxyFieldBuilder() {
        if (ixyBuilder_ == null) {
          ixyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder>(
                  getIxy(),
                  getParentForChildren(),
                  isClean());
          ixy_ = null;
        }
        return ixyBuilder_;
      }

      private choreo.FloatOuterClass.Float64 ixz_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> ixzBuilder_;
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public boolean hasIxz() {
        return ixzBuilder_ != null || ixz_ != null;
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public choreo.FloatOuterClass.Float64 getIxz() {
        if (ixzBuilder_ == null) {
          return ixz_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : ixz_;
        } else {
          return ixzBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public Builder setIxz(choreo.FloatOuterClass.Float64 value) {
        if (ixzBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ixz_ = value;
          onChanged();
        } else {
          ixzBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public Builder setIxz(
          choreo.FloatOuterClass.Float64.Builder builderForValue) {
        if (ixzBuilder_ == null) {
          ixz_ = builderForValue.build();
          onChanged();
        } else {
          ixzBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public Builder mergeIxz(choreo.FloatOuterClass.Float64 value) {
        if (ixzBuilder_ == null) {
          if (ixz_ != null) {
            ixz_ =
              choreo.FloatOuterClass.Float64.newBuilder(ixz_).mergeFrom(value).buildPartial();
          } else {
            ixz_ = value;
          }
          onChanged();
        } else {
          ixzBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public Builder clearIxz() {
        if (ixzBuilder_ == null) {
          ixz_ = null;
          onChanged();
        } else {
          ixz_ = null;
          ixzBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public choreo.FloatOuterClass.Float64.Builder getIxzBuilder() {
        
        onChanged();
        return getIxzFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      public choreo.FloatOuterClass.Float64OrBuilder getIxzOrBuilder() {
        if (ixzBuilder_ != null) {
          return ixzBuilder_.getMessageOrBuilder();
        } else {
          return ixz_ == null ?
              choreo.FloatOuterClass.Float64.getDefaultInstance() : ixz_;
        }
      }
      /**
       * <code>.choreo.Float64 ixz = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> 
          getIxzFieldBuilder() {
        if (ixzBuilder_ == null) {
          ixzBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder>(
                  getIxz(),
                  getParentForChildren(),
                  isClean());
          ixz_ = null;
        }
        return ixzBuilder_;
      }

      private choreo.FloatOuterClass.Float64 iyy_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> iyyBuilder_;
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public boolean hasIyy() {
        return iyyBuilder_ != null || iyy_ != null;
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public choreo.FloatOuterClass.Float64 getIyy() {
        if (iyyBuilder_ == null) {
          return iyy_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : iyy_;
        } else {
          return iyyBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public Builder setIyy(choreo.FloatOuterClass.Float64 value) {
        if (iyyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          iyy_ = value;
          onChanged();
        } else {
          iyyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public Builder setIyy(
          choreo.FloatOuterClass.Float64.Builder builderForValue) {
        if (iyyBuilder_ == null) {
          iyy_ = builderForValue.build();
          onChanged();
        } else {
          iyyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public Builder mergeIyy(choreo.FloatOuterClass.Float64 value) {
        if (iyyBuilder_ == null) {
          if (iyy_ != null) {
            iyy_ =
              choreo.FloatOuterClass.Float64.newBuilder(iyy_).mergeFrom(value).buildPartial();
          } else {
            iyy_ = value;
          }
          onChanged();
        } else {
          iyyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public Builder clearIyy() {
        if (iyyBuilder_ == null) {
          iyy_ = null;
          onChanged();
        } else {
          iyy_ = null;
          iyyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public choreo.FloatOuterClass.Float64.Builder getIyyBuilder() {
        
        onChanged();
        return getIyyFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      public choreo.FloatOuterClass.Float64OrBuilder getIyyOrBuilder() {
        if (iyyBuilder_ != null) {
          return iyyBuilder_.getMessageOrBuilder();
        } else {
          return iyy_ == null ?
              choreo.FloatOuterClass.Float64.getDefaultInstance() : iyy_;
        }
      }
      /**
       * <code>.choreo.Float64 iyy = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> 
          getIyyFieldBuilder() {
        if (iyyBuilder_ == null) {
          iyyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder>(
                  getIyy(),
                  getParentForChildren(),
                  isClean());
          iyy_ = null;
        }
        return iyyBuilder_;
      }

      private choreo.FloatOuterClass.Float64 iyz_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> iyzBuilder_;
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public boolean hasIyz() {
        return iyzBuilder_ != null || iyz_ != null;
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public choreo.FloatOuterClass.Float64 getIyz() {
        if (iyzBuilder_ == null) {
          return iyz_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : iyz_;
        } else {
          return iyzBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public Builder setIyz(choreo.FloatOuterClass.Float64 value) {
        if (iyzBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          iyz_ = value;
          onChanged();
        } else {
          iyzBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public Builder setIyz(
          choreo.FloatOuterClass.Float64.Builder builderForValue) {
        if (iyzBuilder_ == null) {
          iyz_ = builderForValue.build();
          onChanged();
        } else {
          iyzBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public Builder mergeIyz(choreo.FloatOuterClass.Float64 value) {
        if (iyzBuilder_ == null) {
          if (iyz_ != null) {
            iyz_ =
              choreo.FloatOuterClass.Float64.newBuilder(iyz_).mergeFrom(value).buildPartial();
          } else {
            iyz_ = value;
          }
          onChanged();
        } else {
          iyzBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public Builder clearIyz() {
        if (iyzBuilder_ == null) {
          iyz_ = null;
          onChanged();
        } else {
          iyz_ = null;
          iyzBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public choreo.FloatOuterClass.Float64.Builder getIyzBuilder() {
        
        onChanged();
        return getIyzFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      public choreo.FloatOuterClass.Float64OrBuilder getIyzOrBuilder() {
        if (iyzBuilder_ != null) {
          return iyzBuilder_.getMessageOrBuilder();
        } else {
          return iyz_ == null ?
              choreo.FloatOuterClass.Float64.getDefaultInstance() : iyz_;
        }
      }
      /**
       * <code>.choreo.Float64 iyz = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> 
          getIyzFieldBuilder() {
        if (iyzBuilder_ == null) {
          iyzBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder>(
                  getIyz(),
                  getParentForChildren(),
                  isClean());
          iyz_ = null;
        }
        return iyzBuilder_;
      }

      private choreo.FloatOuterClass.Float64 izz_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> izzBuilder_;
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public boolean hasIzz() {
        return izzBuilder_ != null || izz_ != null;
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public choreo.FloatOuterClass.Float64 getIzz() {
        if (izzBuilder_ == null) {
          return izz_ == null ? choreo.FloatOuterClass.Float64.getDefaultInstance() : izz_;
        } else {
          return izzBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public Builder setIzz(choreo.FloatOuterClass.Float64 value) {
        if (izzBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          izz_ = value;
          onChanged();
        } else {
          izzBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public Builder setIzz(
          choreo.FloatOuterClass.Float64.Builder builderForValue) {
        if (izzBuilder_ == null) {
          izz_ = builderForValue.build();
          onChanged();
        } else {
          izzBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public Builder mergeIzz(choreo.FloatOuterClass.Float64 value) {
        if (izzBuilder_ == null) {
          if (izz_ != null) {
            izz_ =
              choreo.FloatOuterClass.Float64.newBuilder(izz_).mergeFrom(value).buildPartial();
          } else {
            izz_ = value;
          }
          onChanged();
        } else {
          izzBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public Builder clearIzz() {
        if (izzBuilder_ == null) {
          izz_ = null;
          onChanged();
        } else {
          izz_ = null;
          izzBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public choreo.FloatOuterClass.Float64.Builder getIzzBuilder() {
        
        onChanged();
        return getIzzFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      public choreo.FloatOuterClass.Float64OrBuilder getIzzOrBuilder() {
        if (izzBuilder_ != null) {
          return izzBuilder_.getMessageOrBuilder();
        } else {
          return izz_ == null ?
              choreo.FloatOuterClass.Float64.getDefaultInstance() : izz_;
        }
      }
      /**
       * <code>.choreo.Float64 izz = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder> 
          getIzzFieldBuilder() {
        if (izzBuilder_ == null) {
          izzBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.FloatOuterClass.Float64, choreo.FloatOuterClass.Float64.Builder, choreo.FloatOuterClass.Float64OrBuilder>(
                  getIzz(),
                  getParentForChildren(),
                  isClean());
          izz_ = null;
        }
        return izzBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:choreo.Inertia)
    }

    // @@protoc_insertion_point(class_scope:choreo.Inertia)
    private static final choreo.InertiaOuterClass.Inertia DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new choreo.InertiaOuterClass.Inertia();
    }

    public static choreo.InertiaOuterClass.Inertia getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Inertia>
        PARSER = new com.google.protobuf.AbstractParser<Inertia>() {
      public Inertia parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Inertia(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Inertia> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Inertia> getParserForType() {
      return PARSER;
    }

    public choreo.InertiaOuterClass.Inertia getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_choreo_InertiaStamped_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_choreo_InertiaStamped_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_choreo_Inertia_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_choreo_Inertia_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027geometric/inertia.proto\022\006choreo\032\026primi" +
      "tive/header.proto\032\025primitive/float.proto" +
      "\032\026geometric/vector.proto\"R\n\016InertiaStamp" +
      "ed\022\036\n\006header\030\001 \001(\0132\016.choreo.Header\022 \n\007in" +
      "ertia\030\002 \001(\0132\017.choreo.Inertia\"\367\001\n\007Inertia" +
      "\022\032\n\001m\030\001 \001(\0132\017.choreo.Float64\022\034\n\003com\030\002 \001(" +
      "\0132\017.choreo.Vector3\022\034\n\003ixx\030\003 \001(\0132\017.choreo" +
      ".Float64\022\034\n\003ixy\030\004 \001(\0132\017.choreo.Float64\022\034" +
      "\n\003ixz\030\005 \001(\0132\017.choreo.Float64\022\034\n\003iyy\030\007 \001(" +
      "\0132\017.choreo.Float64\022\034\n\003iyz\030\010 \001(\0132\017.choreo",
      ".Float64\022\034\n\003izz\030\006 \001(\0132\017.choreo.Float64B1" +
      "Z/github.com/RobotStudio/choreo-msg/msg/" +
      "geometricb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          choreo.HeaderOuterClass.getDescriptor(),
          choreo.FloatOuterClass.getDescriptor(),
          choreo.Vector.getDescriptor(),
        }, assigner);
    internal_static_choreo_InertiaStamped_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_choreo_InertiaStamped_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_choreo_InertiaStamped_descriptor,
        new java.lang.String[] { "Header", "Inertia", });
    internal_static_choreo_Inertia_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_choreo_Inertia_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_choreo_Inertia_descriptor,
        new java.lang.String[] { "M", "Com", "Ixx", "Ixy", "Ixz", "Iyy", "Iyz", "Izz", });
    choreo.HeaderOuterClass.getDescriptor();
    choreo.FloatOuterClass.getDescriptor();
    choreo.Vector.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
