// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geometric/transform.proto

package choreo;

public final class TransformOuterClass {
  private TransformOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransformStampedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:choreo.TransformStamped)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.choreo.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    choreo.HeaderOuterClass.Header getHeader();
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.choreo.Transform transform = 2;</code>
     */
    boolean hasTransform();
    /**
     * <code>.choreo.Transform transform = 2;</code>
     */
    choreo.TransformOuterClass.Transform getTransform();
    /**
     * <code>.choreo.Transform transform = 2;</code>
     */
    choreo.TransformOuterClass.TransformOrBuilder getTransformOrBuilder();
  }
  /**
   * Protobuf type {@code choreo.TransformStamped}
   */
  public  static final class TransformStamped extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:choreo.TransformStamped)
      TransformStampedOrBuilder {
    // Use TransformStamped.newBuilder() to construct.
    private TransformStamped(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransformStamped() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransformStamped(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              choreo.HeaderOuterClass.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(choreo.HeaderOuterClass.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              choreo.TransformOuterClass.Transform.Builder subBuilder = null;
              if (transform_ != null) {
                subBuilder = transform_.toBuilder();
              }
              transform_ = input.readMessage(choreo.TransformOuterClass.Transform.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transform_);
                transform_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return choreo.TransformOuterClass.internal_static_choreo_TransformStamped_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return choreo.TransformOuterClass.internal_static_choreo_TransformStamped_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              choreo.TransformOuterClass.TransformStamped.class, choreo.TransformOuterClass.TransformStamped.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private choreo.HeaderOuterClass.Header header_;
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public choreo.HeaderOuterClass.Header getHeader() {
      return header_ == null ? choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.choreo.Header header = 1;</code>
     */
    public choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int TRANSFORM_FIELD_NUMBER = 2;
    private choreo.TransformOuterClass.Transform transform_;
    /**
     * <code>.choreo.Transform transform = 2;</code>
     */
    public boolean hasTransform() {
      return transform_ != null;
    }
    /**
     * <code>.choreo.Transform transform = 2;</code>
     */
    public choreo.TransformOuterClass.Transform getTransform() {
      return transform_ == null ? choreo.TransformOuterClass.Transform.getDefaultInstance() : transform_;
    }
    /**
     * <code>.choreo.Transform transform = 2;</code>
     */
    public choreo.TransformOuterClass.TransformOrBuilder getTransformOrBuilder() {
      return getTransform();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (transform_ != null) {
        output.writeMessage(2, getTransform());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (transform_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTransform());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof choreo.TransformOuterClass.TransformStamped)) {
        return super.equals(obj);
      }
      choreo.TransformOuterClass.TransformStamped other = (choreo.TransformOuterClass.TransformStamped) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasTransform() == other.hasTransform());
      if (hasTransform()) {
        result = result && getTransform()
            .equals(other.getTransform());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasTransform()) {
        hash = (37 * hash) + TRANSFORM_FIELD_NUMBER;
        hash = (53 * hash) + getTransform().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.TransformOuterClass.TransformStamped parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static choreo.TransformOuterClass.TransformStamped parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.TransformOuterClass.TransformStamped parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(choreo.TransformOuterClass.TransformStamped prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code choreo.TransformStamped}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:choreo.TransformStamped)
        choreo.TransformOuterClass.TransformStampedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return choreo.TransformOuterClass.internal_static_choreo_TransformStamped_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return choreo.TransformOuterClass.internal_static_choreo_TransformStamped_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                choreo.TransformOuterClass.TransformStamped.class, choreo.TransformOuterClass.TransformStamped.Builder.class);
      }

      // Construct using choreo.TransformOuterClass.TransformStamped.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (transformBuilder_ == null) {
          transform_ = null;
        } else {
          transform_ = null;
          transformBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return choreo.TransformOuterClass.internal_static_choreo_TransformStamped_descriptor;
      }

      public choreo.TransformOuterClass.TransformStamped getDefaultInstanceForType() {
        return choreo.TransformOuterClass.TransformStamped.getDefaultInstance();
      }

      public choreo.TransformOuterClass.TransformStamped build() {
        choreo.TransformOuterClass.TransformStamped result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public choreo.TransformOuterClass.TransformStamped buildPartial() {
        choreo.TransformOuterClass.TransformStamped result = new choreo.TransformOuterClass.TransformStamped(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (transformBuilder_ == null) {
          result.transform_ = transform_;
        } else {
          result.transform_ = transformBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof choreo.TransformOuterClass.TransformStamped) {
          return mergeFrom((choreo.TransformOuterClass.TransformStamped)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(choreo.TransformOuterClass.TransformStamped other) {
        if (other == choreo.TransformOuterClass.TransformStamped.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasTransform()) {
          mergeTransform(other.getTransform());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        choreo.TransformOuterClass.TransformStamped parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (choreo.TransformOuterClass.TransformStamped) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private choreo.HeaderOuterClass.Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder setHeader(choreo.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder setHeader(
          choreo.HeaderOuterClass.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder mergeHeader(choreo.HeaderOuterClass.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              choreo.HeaderOuterClass.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      public choreo.HeaderOuterClass.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              choreo.HeaderOuterClass.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.choreo.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.HeaderOuterClass.Header, choreo.HeaderOuterClass.Header.Builder, choreo.HeaderOuterClass.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private choreo.TransformOuterClass.Transform transform_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.TransformOuterClass.Transform, choreo.TransformOuterClass.Transform.Builder, choreo.TransformOuterClass.TransformOrBuilder> transformBuilder_;
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public boolean hasTransform() {
        return transformBuilder_ != null || transform_ != null;
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public choreo.TransformOuterClass.Transform getTransform() {
        if (transformBuilder_ == null) {
          return transform_ == null ? choreo.TransformOuterClass.Transform.getDefaultInstance() : transform_;
        } else {
          return transformBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public Builder setTransform(choreo.TransformOuterClass.Transform value) {
        if (transformBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transform_ = value;
          onChanged();
        } else {
          transformBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public Builder setTransform(
          choreo.TransformOuterClass.Transform.Builder builderForValue) {
        if (transformBuilder_ == null) {
          transform_ = builderForValue.build();
          onChanged();
        } else {
          transformBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public Builder mergeTransform(choreo.TransformOuterClass.Transform value) {
        if (transformBuilder_ == null) {
          if (transform_ != null) {
            transform_ =
              choreo.TransformOuterClass.Transform.newBuilder(transform_).mergeFrom(value).buildPartial();
          } else {
            transform_ = value;
          }
          onChanged();
        } else {
          transformBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public Builder clearTransform() {
        if (transformBuilder_ == null) {
          transform_ = null;
          onChanged();
        } else {
          transform_ = null;
          transformBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public choreo.TransformOuterClass.Transform.Builder getTransformBuilder() {
        
        onChanged();
        return getTransformFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      public choreo.TransformOuterClass.TransformOrBuilder getTransformOrBuilder() {
        if (transformBuilder_ != null) {
          return transformBuilder_.getMessageOrBuilder();
        } else {
          return transform_ == null ?
              choreo.TransformOuterClass.Transform.getDefaultInstance() : transform_;
        }
      }
      /**
       * <code>.choreo.Transform transform = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.TransformOuterClass.Transform, choreo.TransformOuterClass.Transform.Builder, choreo.TransformOuterClass.TransformOrBuilder> 
          getTransformFieldBuilder() {
        if (transformBuilder_ == null) {
          transformBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.TransformOuterClass.Transform, choreo.TransformOuterClass.Transform.Builder, choreo.TransformOuterClass.TransformOrBuilder>(
                  getTransform(),
                  getParentForChildren(),
                  isClean());
          transform_ = null;
        }
        return transformBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:choreo.TransformStamped)
    }

    // @@protoc_insertion_point(class_scope:choreo.TransformStamped)
    private static final choreo.TransformOuterClass.TransformStamped DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new choreo.TransformOuterClass.TransformStamped();
    }

    public static choreo.TransformOuterClass.TransformStamped getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransformStamped>
        PARSER = new com.google.protobuf.AbstractParser<TransformStamped>() {
      public TransformStamped parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransformStamped(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransformStamped> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransformStamped> getParserForType() {
      return PARSER;
    }

    public choreo.TransformOuterClass.TransformStamped getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransformOrBuilder extends
      // @@protoc_insertion_point(interface_extends:choreo.Transform)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.choreo.Vector3 translation = 1;</code>
     */
    boolean hasTranslation();
    /**
     * <code>.choreo.Vector3 translation = 1;</code>
     */
    choreo.Vector.Vector3 getTranslation();
    /**
     * <code>.choreo.Vector3 translation = 1;</code>
     */
    choreo.Vector.Vector3OrBuilder getTranslationOrBuilder();

    /**
     * <code>.choreo.Quaternion rotation = 2;</code>
     */
    boolean hasRotation();
    /**
     * <code>.choreo.Quaternion rotation = 2;</code>
     */
    choreo.QuaternionOuterClass.Quaternion getRotation();
    /**
     * <code>.choreo.Quaternion rotation = 2;</code>
     */
    choreo.QuaternionOuterClass.QuaternionOrBuilder getRotationOrBuilder();
  }
  /**
   * Protobuf type {@code choreo.Transform}
   */
  public  static final class Transform extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:choreo.Transform)
      TransformOrBuilder {
    // Use Transform.newBuilder() to construct.
    private Transform(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transform() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Transform(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              choreo.Vector.Vector3.Builder subBuilder = null;
              if (translation_ != null) {
                subBuilder = translation_.toBuilder();
              }
              translation_ = input.readMessage(choreo.Vector.Vector3.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(translation_);
                translation_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              choreo.QuaternionOuterClass.Quaternion.Builder subBuilder = null;
              if (rotation_ != null) {
                subBuilder = rotation_.toBuilder();
              }
              rotation_ = input.readMessage(choreo.QuaternionOuterClass.Quaternion.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rotation_);
                rotation_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return choreo.TransformOuterClass.internal_static_choreo_Transform_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return choreo.TransformOuterClass.internal_static_choreo_Transform_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              choreo.TransformOuterClass.Transform.class, choreo.TransformOuterClass.Transform.Builder.class);
    }

    public static final int TRANSLATION_FIELD_NUMBER = 1;
    private choreo.Vector.Vector3 translation_;
    /**
     * <code>.choreo.Vector3 translation = 1;</code>
     */
    public boolean hasTranslation() {
      return translation_ != null;
    }
    /**
     * <code>.choreo.Vector3 translation = 1;</code>
     */
    public choreo.Vector.Vector3 getTranslation() {
      return translation_ == null ? choreo.Vector.Vector3.getDefaultInstance() : translation_;
    }
    /**
     * <code>.choreo.Vector3 translation = 1;</code>
     */
    public choreo.Vector.Vector3OrBuilder getTranslationOrBuilder() {
      return getTranslation();
    }

    public static final int ROTATION_FIELD_NUMBER = 2;
    private choreo.QuaternionOuterClass.Quaternion rotation_;
    /**
     * <code>.choreo.Quaternion rotation = 2;</code>
     */
    public boolean hasRotation() {
      return rotation_ != null;
    }
    /**
     * <code>.choreo.Quaternion rotation = 2;</code>
     */
    public choreo.QuaternionOuterClass.Quaternion getRotation() {
      return rotation_ == null ? choreo.QuaternionOuterClass.Quaternion.getDefaultInstance() : rotation_;
    }
    /**
     * <code>.choreo.Quaternion rotation = 2;</code>
     */
    public choreo.QuaternionOuterClass.QuaternionOrBuilder getRotationOrBuilder() {
      return getRotation();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (translation_ != null) {
        output.writeMessage(1, getTranslation());
      }
      if (rotation_ != null) {
        output.writeMessage(2, getRotation());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (translation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTranslation());
      }
      if (rotation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRotation());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof choreo.TransformOuterClass.Transform)) {
        return super.equals(obj);
      }
      choreo.TransformOuterClass.Transform other = (choreo.TransformOuterClass.Transform) obj;

      boolean result = true;
      result = result && (hasTranslation() == other.hasTranslation());
      if (hasTranslation()) {
        result = result && getTranslation()
            .equals(other.getTranslation());
      }
      result = result && (hasRotation() == other.hasRotation());
      if (hasRotation()) {
        result = result && getRotation()
            .equals(other.getRotation());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTranslation()) {
        hash = (37 * hash) + TRANSLATION_FIELD_NUMBER;
        hash = (53 * hash) + getTranslation().hashCode();
      }
      if (hasRotation()) {
        hash = (37 * hash) + ROTATION_FIELD_NUMBER;
        hash = (53 * hash) + getRotation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static choreo.TransformOuterClass.Transform parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.TransformOuterClass.Transform parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static choreo.TransformOuterClass.Transform parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static choreo.TransformOuterClass.Transform parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(choreo.TransformOuterClass.Transform prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code choreo.Transform}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:choreo.Transform)
        choreo.TransformOuterClass.TransformOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return choreo.TransformOuterClass.internal_static_choreo_Transform_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return choreo.TransformOuterClass.internal_static_choreo_Transform_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                choreo.TransformOuterClass.Transform.class, choreo.TransformOuterClass.Transform.Builder.class);
      }

      // Construct using choreo.TransformOuterClass.Transform.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (translationBuilder_ == null) {
          translation_ = null;
        } else {
          translation_ = null;
          translationBuilder_ = null;
        }
        if (rotationBuilder_ == null) {
          rotation_ = null;
        } else {
          rotation_ = null;
          rotationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return choreo.TransformOuterClass.internal_static_choreo_Transform_descriptor;
      }

      public choreo.TransformOuterClass.Transform getDefaultInstanceForType() {
        return choreo.TransformOuterClass.Transform.getDefaultInstance();
      }

      public choreo.TransformOuterClass.Transform build() {
        choreo.TransformOuterClass.Transform result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public choreo.TransformOuterClass.Transform buildPartial() {
        choreo.TransformOuterClass.Transform result = new choreo.TransformOuterClass.Transform(this);
        if (translationBuilder_ == null) {
          result.translation_ = translation_;
        } else {
          result.translation_ = translationBuilder_.build();
        }
        if (rotationBuilder_ == null) {
          result.rotation_ = rotation_;
        } else {
          result.rotation_ = rotationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof choreo.TransformOuterClass.Transform) {
          return mergeFrom((choreo.TransformOuterClass.Transform)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(choreo.TransformOuterClass.Transform other) {
        if (other == choreo.TransformOuterClass.Transform.getDefaultInstance()) return this;
        if (other.hasTranslation()) {
          mergeTranslation(other.getTranslation());
        }
        if (other.hasRotation()) {
          mergeRotation(other.getRotation());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        choreo.TransformOuterClass.Transform parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (choreo.TransformOuterClass.Transform) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private choreo.Vector.Vector3 translation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.Vector.Vector3, choreo.Vector.Vector3.Builder, choreo.Vector.Vector3OrBuilder> translationBuilder_;
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public boolean hasTranslation() {
        return translationBuilder_ != null || translation_ != null;
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public choreo.Vector.Vector3 getTranslation() {
        if (translationBuilder_ == null) {
          return translation_ == null ? choreo.Vector.Vector3.getDefaultInstance() : translation_;
        } else {
          return translationBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public Builder setTranslation(choreo.Vector.Vector3 value) {
        if (translationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          translation_ = value;
          onChanged();
        } else {
          translationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public Builder setTranslation(
          choreo.Vector.Vector3.Builder builderForValue) {
        if (translationBuilder_ == null) {
          translation_ = builderForValue.build();
          onChanged();
        } else {
          translationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public Builder mergeTranslation(choreo.Vector.Vector3 value) {
        if (translationBuilder_ == null) {
          if (translation_ != null) {
            translation_ =
              choreo.Vector.Vector3.newBuilder(translation_).mergeFrom(value).buildPartial();
          } else {
            translation_ = value;
          }
          onChanged();
        } else {
          translationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public Builder clearTranslation() {
        if (translationBuilder_ == null) {
          translation_ = null;
          onChanged();
        } else {
          translation_ = null;
          translationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public choreo.Vector.Vector3.Builder getTranslationBuilder() {
        
        onChanged();
        return getTranslationFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      public choreo.Vector.Vector3OrBuilder getTranslationOrBuilder() {
        if (translationBuilder_ != null) {
          return translationBuilder_.getMessageOrBuilder();
        } else {
          return translation_ == null ?
              choreo.Vector.Vector3.getDefaultInstance() : translation_;
        }
      }
      /**
       * <code>.choreo.Vector3 translation = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.Vector.Vector3, choreo.Vector.Vector3.Builder, choreo.Vector.Vector3OrBuilder> 
          getTranslationFieldBuilder() {
        if (translationBuilder_ == null) {
          translationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.Vector.Vector3, choreo.Vector.Vector3.Builder, choreo.Vector.Vector3OrBuilder>(
                  getTranslation(),
                  getParentForChildren(),
                  isClean());
          translation_ = null;
        }
        return translationBuilder_;
      }

      private choreo.QuaternionOuterClass.Quaternion rotation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.QuaternionOuterClass.Quaternion, choreo.QuaternionOuterClass.Quaternion.Builder, choreo.QuaternionOuterClass.QuaternionOrBuilder> rotationBuilder_;
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public boolean hasRotation() {
        return rotationBuilder_ != null || rotation_ != null;
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public choreo.QuaternionOuterClass.Quaternion getRotation() {
        if (rotationBuilder_ == null) {
          return rotation_ == null ? choreo.QuaternionOuterClass.Quaternion.getDefaultInstance() : rotation_;
        } else {
          return rotationBuilder_.getMessage();
        }
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public Builder setRotation(choreo.QuaternionOuterClass.Quaternion value) {
        if (rotationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rotation_ = value;
          onChanged();
        } else {
          rotationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public Builder setRotation(
          choreo.QuaternionOuterClass.Quaternion.Builder builderForValue) {
        if (rotationBuilder_ == null) {
          rotation_ = builderForValue.build();
          onChanged();
        } else {
          rotationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public Builder mergeRotation(choreo.QuaternionOuterClass.Quaternion value) {
        if (rotationBuilder_ == null) {
          if (rotation_ != null) {
            rotation_ =
              choreo.QuaternionOuterClass.Quaternion.newBuilder(rotation_).mergeFrom(value).buildPartial();
          } else {
            rotation_ = value;
          }
          onChanged();
        } else {
          rotationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public Builder clearRotation() {
        if (rotationBuilder_ == null) {
          rotation_ = null;
          onChanged();
        } else {
          rotation_ = null;
          rotationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public choreo.QuaternionOuterClass.Quaternion.Builder getRotationBuilder() {
        
        onChanged();
        return getRotationFieldBuilder().getBuilder();
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      public choreo.QuaternionOuterClass.QuaternionOrBuilder getRotationOrBuilder() {
        if (rotationBuilder_ != null) {
          return rotationBuilder_.getMessageOrBuilder();
        } else {
          return rotation_ == null ?
              choreo.QuaternionOuterClass.Quaternion.getDefaultInstance() : rotation_;
        }
      }
      /**
       * <code>.choreo.Quaternion rotation = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          choreo.QuaternionOuterClass.Quaternion, choreo.QuaternionOuterClass.Quaternion.Builder, choreo.QuaternionOuterClass.QuaternionOrBuilder> 
          getRotationFieldBuilder() {
        if (rotationBuilder_ == null) {
          rotationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              choreo.QuaternionOuterClass.Quaternion, choreo.QuaternionOuterClass.Quaternion.Builder, choreo.QuaternionOuterClass.QuaternionOrBuilder>(
                  getRotation(),
                  getParentForChildren(),
                  isClean());
          rotation_ = null;
        }
        return rotationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:choreo.Transform)
    }

    // @@protoc_insertion_point(class_scope:choreo.Transform)
    private static final choreo.TransformOuterClass.Transform DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new choreo.TransformOuterClass.Transform();
    }

    public static choreo.TransformOuterClass.Transform getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transform>
        PARSER = new com.google.protobuf.AbstractParser<Transform>() {
      public Transform parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Transform(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transform> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transform> getParserForType() {
      return PARSER;
    }

    public choreo.TransformOuterClass.Transform getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_choreo_TransformStamped_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_choreo_TransformStamped_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_choreo_Transform_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_choreo_Transform_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031geometric/transform.proto\022\006choreo\032\026pri" +
      "mitive/header.proto\032\026geometric/vector.pr" +
      "oto\032\032geometric/quaternion.proto\"X\n\020Trans" +
      "formStamped\022\036\n\006header\030\001 \001(\0132\016.choreo.Hea" +
      "der\022$\n\ttransform\030\002 \001(\0132\021.choreo.Transfor" +
      "m\"W\n\tTransform\022$\n\013translation\030\001 \001(\0132\017.ch" +
      "oreo.Vector3\022$\n\010rotation\030\002 \001(\0132\022.choreo." +
      "QuaternionBIZGgithub.com/RobotStudio/cho" +
      "reo-msg/msg/geometric;rs.choreo.msg.geom" +
      "etricb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          choreo.HeaderOuterClass.getDescriptor(),
          choreo.Vector.getDescriptor(),
          choreo.QuaternionOuterClass.getDescriptor(),
        }, assigner);
    internal_static_choreo_TransformStamped_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_choreo_TransformStamped_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_choreo_TransformStamped_descriptor,
        new java.lang.String[] { "Header", "Transform", });
    internal_static_choreo_Transform_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_choreo_Transform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_choreo_Transform_descriptor,
        new java.lang.String[] { "Translation", "Rotation", });
    choreo.HeaderOuterClass.getDescriptor();
    choreo.Vector.getDescriptor();
    choreo.QuaternionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
