// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geometric/inertia.proto

/*
Package choreo is a generated protocol buffer package.

It is generated from these files:
	geometric/inertia.proto

It has these top-level messages:
	InertiaStamped
	Inertia
*/
package choreo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import choreo1 "primitive"
import choreo2 "primitive"
import choreo3 "geometric"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InertiaStamped struct {
	Header  *choreo1.Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Inertia *Inertia        `protobuf:"bytes,2,opt,name=inertia" json:"inertia,omitempty"`
}

func (m *InertiaStamped) Reset()                    { *m = InertiaStamped{} }
func (m *InertiaStamped) String() string            { return proto.CompactTextString(m) }
func (*InertiaStamped) ProtoMessage()               {}
func (*InertiaStamped) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InertiaStamped) GetHeader() *choreo1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InertiaStamped) GetInertia() *Inertia {
	if m != nil {
		return m.Inertia
	}
	return nil
}

type Inertia struct {
	M   *choreo2.Float64 `protobuf:"bytes,1,opt,name=m" json:"m,omitempty"`
	Com *choreo3.Vector3 `protobuf:"bytes,2,opt,name=com" json:"com,omitempty"`
	Ixx *choreo2.Float64 `protobuf:"bytes,3,opt,name=ixx" json:"ixx,omitempty"`
	Ixy *choreo2.Float64 `protobuf:"bytes,4,opt,name=ixy" json:"ixy,omitempty"`
	Ixz *choreo2.Float64 `protobuf:"bytes,5,opt,name=ixz" json:"ixz,omitempty"`
	Iyy *choreo2.Float64 `protobuf:"bytes,7,opt,name=iyy" json:"iyy,omitempty"`
	Iyz *choreo2.Float64 `protobuf:"bytes,8,opt,name=iyz" json:"iyz,omitempty"`
	Izz *choreo2.Float64 `protobuf:"bytes,6,opt,name=izz" json:"izz,omitempty"`
}

func (m *Inertia) Reset()                    { *m = Inertia{} }
func (m *Inertia) String() string            { return proto.CompactTextString(m) }
func (*Inertia) ProtoMessage()               {}
func (*Inertia) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Inertia) GetM() *choreo2.Float64 {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *Inertia) GetCom() *choreo3.Vector3 {
	if m != nil {
		return m.Com
	}
	return nil
}

func (m *Inertia) GetIxx() *choreo2.Float64 {
	if m != nil {
		return m.Ixx
	}
	return nil
}

func (m *Inertia) GetIxy() *choreo2.Float64 {
	if m != nil {
		return m.Ixy
	}
	return nil
}

func (m *Inertia) GetIxz() *choreo2.Float64 {
	if m != nil {
		return m.Ixz
	}
	return nil
}

func (m *Inertia) GetIyy() *choreo2.Float64 {
	if m != nil {
		return m.Iyy
	}
	return nil
}

func (m *Inertia) GetIyz() *choreo2.Float64 {
	if m != nil {
		return m.Iyz
	}
	return nil
}

func (m *Inertia) GetIzz() *choreo2.Float64 {
	if m != nil {
		return m.Izz
	}
	return nil
}

func init() {
	proto.RegisterType((*InertiaStamped)(nil), "choreo.InertiaStamped")
	proto.RegisterType((*Inertia)(nil), "choreo.Inertia")
}

func init() { proto.RegisterFile("geometric/inertia.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0x56, 0x77, 0x25, 0x42, 0x85, 0x80, 0x75, 0x28, 0x08, 0xda, 0x83, 0xe8, 0x65,
	0x0b, 0x56, 0x7c, 0x04, 0xd1, 0xeb, 0x0a, 0xde, 0xd7, 0x74, 0xb4, 0x01, 0xe3, 0x2c, 0x21, 0x94,
	0x26, 0xef, 0xe2, 0xbb, 0x4a, 0x32, 0xa9, 0x05, 0x69, 0xae, 0xff, 0xff, 0xe5, 0xcb, 0x0f, 0x23,
	0x2e, 0x3e, 0x91, 0x0c, 0x3a, 0xab, 0xd5, 0x42, 0x7f, 0xa3, 0x75, 0xba, 0x6f, 0x07, 0x4b, 0x8e,
	0x64, 0xad, 0xd6, 0x64, 0x91, 0x66, 0xd3, 0xc1, 0x6a, 0xa3, 0x9d, 0xde, 0xe0, 0x62, 0x8d, 0xfd,
	0x0a, 0x2d, 0xf7, 0xb3, 0xf3, 0x7d, 0xfe, 0xf1, 0x45, 0xbd, 0xcb, 0xf1, 0x74, 0xef, 0xdb, 0xa0,
	0x72, 0x94, 0xf1, 0xb9, 0x12, 0x93, 0x17, 0xf6, 0xbf, 0xba, 0xde, 0x0c, 0xb8, 0x92, 0x37, 0xa2,
	0x66, 0x21, 0x54, 0x57, 0xd5, 0xed, 0xe9, 0xfd, 0xa4, 0xe5, 0x1f, 0xdb, 0xe7, 0x94, 0x76, 0xb9,
	0x95, 0x77, 0xa2, 0xc9, 0xcb, 0x60, 0x94, 0xc0, 0xb3, 0x1d, 0x98, 0x85, 0xdd, 0xae, 0x9f, 0xff,
	0x8c, 0x44, 0x93, 0x43, 0x79, 0x29, 0x2a, 0x93, 0xcd, 0x7f, 0x0f, 0x9e, 0xe2, 0xd0, 0xc7, 0x87,
	0xae, 0x32, 0xf2, 0x5a, 0x8c, 0x15, 0x99, 0xff, 0xc6, 0xb7, 0x34, 0x79, 0xd9, 0xc5, 0x2e, 0x22,
	0x7a, 0xbb, 0x85, 0xf1, 0x61, 0x47, 0xec, 0x18, 0xf1, 0x70, 0x54, 0x44, 0x3c, 0x23, 0x01, 0x8e,
	0x8b, 0x48, 0x48, 0x88, 0xf7, 0xd0, 0x94, 0x10, 0xcf, 0x16, 0x1f, 0xe0, 0xa4, 0x88, 0xb0, 0x25,
	0x04, 0xa8, 0x4b, 0x48, 0x08, 0xef, 0x75, 0xba, 0xc5, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x90,
	0xee, 0x13, 0xc7, 0xf5, 0x01, 0x00, 0x00,
}
